### ISSUE TITLE
Privacy regulation support

### ISSUE THREAD

**Issue by wenjing** [cncf/sig-security#118]
New regulations have been introduced in various regions trying to formalize privacy protection for users. An example is GDPR (https://eugdpr.org/) in EU.
What do these regulations mean to K8S ecosystem? What gaps or pain points exist for k8s service providers today? If such gaps exist, what are good abstractions or capabilities that we should consider to add in k8s?

I raised this question during KubeCon NA in Seattle on Dec 13. I hope this PR can provide a focal point to continue the discussion.

**Comment by lumjjb** [comment]
Looks like there is interest in this topic, perhaps something like having a discussion forum or topic focused presentations would be helpful too. We probably would need a good way of organizing these so that it can get the right audience.

**Comment by lumjjb** [comment]
Closed due to inactivity.
