### ISSUE TITLE
Presentation: Kamus - secrets encryption/decryption solution

### ISSUE THREAD

**Issue by omerlh** [cncf/sig-security#123]
Hey
Recently we released [Kamus](https://github.com/Soluto/kamus), a solution for secret encryption/decryption for Kubernetes platform. In a high-level overview, Kamus solve a common problem for containerized applications - how to pass secrets securely? Kamus designed to encrypt secrets for a specific application, represented by a service account. Only this application can decrypt the secret, and no one else. By this, Kamus offer a secure, zero-trust, GitOps solution to the problem. The design is inspired by Travis encrypted secrets solution.
I would like to present this project to the working group and get your feedback about it. I would be more than happy to answer any question and provide the required information.

cncf/toc#188

**Comment by dshaw** [comment]
@omerlh Thank you. Lining up available dates for presentations now.

**Comment by dshaw** [comment]
@omerlh We will expect to land our SAFE Presentation Framework next week and will be going through a final iteration of the presentation with the in-toto. It would be great if you or one of your team members could join us. This will serve as onboarding for the model we use when presenting to the WG.

Friday, March 29th at 11am PT

**Comment by omerlh** [comment]
I'm from Israel, not sure I'll be able to join, this time is a bit complex for me. I'll be happy to take a look at the model anyway and send my comments.

**Comment by justincormack** [comment]
Would you be able to present at one of the weekly meetings? These are at 8pm your time (I think) Wednesdays now. See https://github.com/cncf/sig-security/issues/283 for discussion of what to present.

**Comment by rficcaglia** [comment]
@omerlh just checking if you were able to attend today's session and discuss ... no pressure just trying to sketch out agenda ahead of the call

**Comment by omerlh** [comment]
Yeah, I'll be able to attend!

**Comment by lumjjb** [comment]
Presented on 6th November SIG-Security meeting (https://www.youtube.com/watch?v=uzNIZcqOKd4)
