### ISSUE TITLE
landscape: map projects to categories

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#124]
This issue is for further work on https://github.com/cn-security/safe/tree/master/landscape

Placeholder for "finishing" the landscape, here are the next steps we have discussed

Map Security-Related Projects From CNCF Landscape Into draft categories, adjusting categories as needed (split off from https://github.com/cn-security/safe/issues/66, based on comment from @izgeri)

  - Security and Policy solutions
    - [x] SPIFFE / SPIRE - Evan
    - [ ] Notary
    - [ ] TUF
    - [ ] OPA - Torin with updater
  - Projects with Security Concerns
    - [ ] gRPC
  - Platforms (consider sub-projects that can be used stand-alone, such as Envoy, Mixer):
    - [ ] Istio
    - [ ] Kubernetes
- [ ] solicit feedback from the projects themselves

**Comment by izgeri** [comment]
Noting that I spoke to Torin @ OPA today, and he noted that he thinks OPA will fit into both
- Identity & Access Control - Access Controls
- Service Access - Service admittance & admission controllers

We talked about some strategies we are considering for categorizing projects, and I asked him to think about security-related attributes that apply to OPA (even divorced from the landscape sub-categories) to help us figure out how we might map them onto the landscape. That is, we have a sense that they probably belong in the subcategories above, and if we know the project also has attributes X1, X2, and X3, it might give us a sense of how to map those attributes into those subcategories in a way that other projects can also use, or it may highlight for us gaps in our current subcategory definitions.

Also, we are probably due for a brainstorm session on this - I will raise that at the next meeting.

**Comment by ultrasaurus** [comment]
talked to @JustinCappos who has some ideas about how to better articulate the stages of cloud native  tech to divide up the space... I *think* this is consistent with what @izgeri and I talked about when we reviewed the PR, but definitely needs a bit more elaboration to be sure.  

In any case, I agree that as written the "Identity & Access Control" section isn't clear and could be interpreted as for every project, since every project at minimum needs its own access control.

**Comment by ultrasaurus** [comment]
Recently telling someone how we arrived at target audience of *deciders* for whitepaper https://github.com/cncf/sig-security/issues/138 which came from the discussion of the landscape and categories, where the group felt that landscape and security overview whitepaper (https://github.com/cncf/sig-security/issues/138) would have the same target audience.

@izgeri helped find discussion in [SAFE meeting notes  2/22/19](https://docs.google.com/document/d/1WLnEErqODywjkQVTAESpwK8pgIbxsNDp6SqOtw3kjlk/edit#)

**Comment by izgeri** [comment]
[Here are the slides](https://drive.google.com/file/d/13JrAvHoo8j7RrREBMPOcuGvtrZpz87s2/view?usp=sharing) I shared at the 2/22/19 meeting on `Mapping the Security Landscape`

**Comment by JustinCappos** [comment]
@lumjjb and I are still working on our version of this, but we're at a point where it makes sense to have CNCF help us mock up a small part of what the final product would look like.  

We could either do this now for the small part we have done or could wait, depending on what others think makes sense...

**Comment by lumjjb** [comment]
Created issue for work @JustinCappos mentioned, and linking it:

https://github.com/cncf/sig-security/issues/348

**Comment by fkautz** [comment]
Would it make sense to add other service meshes? Neither of the CNCF governed meshes (linkerd, Kuma) are listed but Istio is.

**Comment by lumjjb** [comment]
Closing in favor of #348
