### ISSUE TITLE
KubeCon + CloudNativeCon Barcelona, Spain, May 20 – 23, 2019

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#127]
May 20 – 23, 2019 
Fira Gran Via, Barcelona, Spain 

https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/

Moved links to talks to https://github.com/cncf/sig-security/pull/173

**Comment by justincormack** [comment]
Suggest an evening meeting on Tuesday, as seems to conflict less with other things...

**Comment by fntlnz** [comment]
@ultrasaurus if there's no one else volunteering to organize this in person meeting I can arrange something. 

@justincormack Tues evening works very well for me

**Comment by ultrasaurus** [comment]
@fntlnz  that would be fabulous!  Tues works for me too :)

**Comment by fntlnz** [comment]
So, I will find a place to have all of us doing a Dinner together on Tues 21. Will post here details about it.

**Comment by hannibalhuang** [comment]
would be also great to send out a calendar invitation after the place is sorted out :)

**Comment by fntlnz** [comment]
@hannibalhuang yes!
Here is the form to register your presence!

https://forms.gle/iBFFuaNRbtWjHX7E9

I'll collect the names and book the restaurant for us!

**Comment by fntlnz** [comment]
The restaurant confirmed the reservation for our dinner!

We will meet there at 7.45pm!

Address:  Ocaña, Plaça Reial, 13-15, 08002 Barcelona

Maps: https://goo.gl/maps/vMcbcxGbz9KqXQ9D9

**Comment by ultrasaurus** [comment]
Let's remember to take photos at dinner.  I always forget!

**Comment by fntlnz** [comment]
Here are a couple of photos I got from our tweets during the dinner.
![image](https://user-images.githubusercontent.com/3083633/58313263-71c63300-7e0d-11e9-8093-021ca3bd04d1.png)
![image](https://user-images.githubusercontent.com/3083633/58313310-8efb0180-7e0d-11e9-91c0-3ef7372c3b58.png)

- https://twitter.com/ultrasaurus/status/1130959730250272774
- https://twitter.com/ultrasaurus/status/1130959730250272774

**Comment by fntlnz** [comment]
Here are other photos coming from the tweets at the kubecon.

![image](https://user-images.githubusercontent.com/3083633/58313453-ea2cf400-7e0d-11e9-9b6d-d565766e244d.png)

![image](https://user-images.githubusercontent.com/3083633/58313514-06c92c00-7e0e-11e9-8669-6984e9b00a68.png)

![image](https://user-images.githubusercontent.com/3083633/58313534-15174800-7e0e-11e9-9e2d-c13b14461f55.png)



- https://twitter.com/justincormack/status/1130839349128499201
- https://twitter.com/TechJournalist/status/1130839275304574981
- https://twitter.com/TechJournalist/status/1130838446824742912

**Comment by fntlnz** [comment]
Let's close this @ultrasaurus ?
