### ISSUE TITLE
Onboarding OSS Projects at Google

### ISSUE THREAD

**Issue by ckemper67** [cncf/sig-security#131]
@felixgr from the Google Security team has agreed to give a presentation about the onboarding review process. He recently worked with the Envoy project, so he can put this into the context of onboarding a CNCF project.

We would like 30 minutes on the agenda of our Friday meeting at the end of March, beginning of April.

**Comment by ficcaglia** [comment]
has this been confirmed? very hopeful it has!

**Comment by ckemper67** [comment]
We decided today, that we can take this presentation on April 5th. 30 minutes.

**Comment by ultrasaurus** [comment]
From meeting notes...

Recording:
Part 1 - https://www.dropbox.com/s/nqzn35frc0yw025/zoom_0.mp4?dl=0
Part 2 - https://www.dropbox.com/s/ulmha9vwr6um4bp/zoom_1.mp4?dl=0

slides: https://docs.google.com/presentation/d/1ZzsmHyxmVpr5SFizpYoTIl5b0QZHtx7RZI9LlyPWtQ0/edit#slide=id.p
