### ISSUE TITLE
Migrate to a CNCF SIG officially

### ISSUE THREAD

**Issue by caniszczyk** [cncf/sig-security#144]
CNCF has is governance ducks in a row and recently approved SIGs:
https://github.com/cncf/toc/blob/master/sigs/cncf-sigs.md

The CNCF would like this to be the security/governance SIG sponsored by Liz Rice and Joe Beda.

My proposal would be to migrate this repo to github.com/cncf/sig-security-governance and set it up in a way to be CNCF SIG conformant.

**Comment by lizrice** [comment]
Yay! But my one ask here is that we drop the word "governance" from this SIG's name - that word has way too much association with the governance of projects. From discussion with the group yesterday I don't think they like it either :-)

**Comment by ultrasaurus** [comment]
repo moved, rename PR https://github.com/cncf/sig-security/pull/148 merged!
