### ISSUE TITLE
Need to update slack channel in doc

### ISSUE THREAD

**Issue by karthequian** [cncf/sig-security#150]
The README states: `CNCF Slack #sig-security channel` but there isn't a channel with that name in the k8s slack. If someone can let me know what the right channel is, I'll be happy to update docs and join :)

**Comment by justincormack** [comment]
It is the CNCF Slack not the k8s slack cloud-native.slack.com...

**Comment by karthequian** [comment]
gotcha!! Thanks @justincormack
