### ISSUE TITLE
Investigate the "platform implementer" persona

### ISSUE THREAD

**Issue by ckemper67** [cncf/sig-security#165]
Large cloud users frequently have a "platform team" that is responsible for ensuring that the organization's security and compliance constraints can be met. This is increasingly difficult in a hybrid world where the platform team now needs to track and understand the security and compliance offerings from multiple cloud providers. These "platform teams" need to make sure that guidance and sometimes services are in place that allow the administrator personas to be shielded from the differences across cloud providers.

Cloud Native technologies can provide a common ground to some extent, but they do not shield the administrators from being exposed to the platform specific implementations if the deployment consumes other services provided by the platforms. Blobstore is a frequently cited example and we have CNCF efforts like Rook that can provide an abstraction.

**Comment by lumjjb** [comment]
Creating a link to https://github.com/cncf/sig-security/issues/109.

**Comment by rficcaglia** [comment]
in terms of validating policy "overlap" and maintaining a global overall policy while allowing delegated policy....that was a use case we briefly discussed in the context of https://github.com/cncf/sig-security/issues/196 on the Policy-WG call.

**Comment by lumjjb** [comment]
Resolved by https://github.com/cncf/sig-security/pull/246
