### ISSUE TITLE
[Assessment] in-toto

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#166]
Project Name: in-toto

Github URL: https://github.com/in-toto

Security Provider: yes

- [x] Identify team
   - [x] Project security lead: Santiago Torres Arias
   - [x] Lead Security Reviewer: Sarah Allen (@ultrasaurus)
   - [x] additional reviewers: Justin Cormack, Brandon Lum
- [x] Create slack channel (e.g. #sec-assess-intoto)
- [x] Project lead provides [draft document](https://docs.google.com/document/d/1O3O7eFCTZ_7lLZ9IhHSWFiXhjWf2gPuJbzZ7u0m-9uI/edit#heading=h.oykub2ep8ndw)
- [x] "Dumb question phase" Lead Security Reviewer asks clarifying questions 
- [x] Initial review
- [x] Project lead addresses comments/questions in [draft doc](https://docs.google.com/document/d/1O3O7eFCTZ_7lLZ9IhHSWFiXhjWf2gPuJbzZ7u0m-9uI/edit#)
- [x] Presentation & discussion - TODO Link recording, meeting minutes
- [x] Share draft findings with project - in progress
- [x] Assessment summary and doc checked in https://github.com/cncf/sig-security/tree/master/assessments/projects/in-toto
- [X] CNCF TOC presentation -- July 9, 2019 https://www.youtube.com/watch?v=7R6IfBFg2VA (40:00)

**Comment by JustinCappos** [comment]
The in-toto team has reviewed the documentation and revised the documentation.  I believe we're ready for the assessment team to take the next step

**Comment by ultrasaurus** [comment]
@JustinCappos added checkbox for "Project lead addresses comments/questions in draft doc" (we should add that to the template) -- doesn't block our finalizing the summary, but does block "Assessment summary and doc checked into..."

**Comment by dshaw** [comment]
👍 https://github.com/cncf/sig-security/tree/master/assessments/projects/in-toto

**Comment by lumjjb** [comment]
@ultrasaurus I believe the presentation to the TOC is over? shall we update it and close it out :)

**Comment by ultrasaurus** [comment]
linked video in the issue description
