### ISSUE TITLE
[use case presentation] FinTech K8s

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#169]
@cypherfox volunteered to give a presentation about the security measures in his deployment

German FinTech,,
- highly regulated environment
- customers frequently do audits, often ask questions that don't make sense in cloud context and it's hard to know how to answer them

Presentation:  here's what we did, what could we have done better, is there anything we're doing that others would recommend we do differently

- K8s in rented datacenter, on CoreOS provisioned with Terraform, we develop our own code and also deploy open source services
- try not to have humans in the cluster, automated deployment by CI pipeline,

**Comment by cypherfox** [comment]
The slides are here: https://docs.google.com/presentation/d/1VQVuybbTv_yabAa0OiqjZJkyk0S6yZfq9VhfJeSkC-0/edit?usp=sharing

**Comment by ultrasaurus** [comment]
video: https://www.youtube.com/watch?v=bl7HPOrETh4&list=PLj6h78yzYM2MJRBYu9jUisJIXJvi-8jlp&index=15&t=0s

**Comment by lumjjb** [comment]
Closing issue since presentation is done!
