### ISSUE TITLE
write up the "triage" role...

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#198]
We talked about this in meetings and in the #sig-security-triage channel and need to document exactly what the "triage" role is.  

It appears that we need to give people full write access to the repo, but I think it is fine to trust people to only change things within their role.  In the unlikely event that we have a bad actor, then the admin/co-chair would simply remove access.  

Suggest we add to [roles.md](https://github.com/cncf/sig-security/blob/master/governance/roles.md)

**Comment by solrac901** [comment]
Roles reviewed definition are clear hat are the next steps? Define the Chair, Technical Leads based on ? Thanks :)

**Comment by ultrasaurus** [comment]
Roles.md needs to include new “triage” team responsibilities — make/assign
labels, give feedback or add content to issues to ensure we’re following
process — should be covered in meeting note past 2-4 weeks

**Comment by ultrasaurus** [comment]
Digging through [notes](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#):
* Issue triage and curation:
  * assign labels
  * comment where issues need more detail
* suggest proposals or suggestions for discussion at working session meetings
* join slack channel #sig-security-triage

**Comment by lumjjb** [comment]
Looks like this is addressed by https://github.com/cncf/sig-security/pull/219! Doing some triage on the triage issue :)
