### ISSUE TITLE
KubeCon + CloudNativeCon, Shanghai, China - Jun 24 - 26, 2019

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#200]
June 24-26, 2019
Shanghai Expo Centre, Shanghai, China

https://www.lfasiallc.com/events/kubecon-cloudnativecon-china-2019/

Let's try to get a group together to meet up! Comment if you're going to be there!

**Comment by hannibalhuang** [comment]
i will be there

**Comment by mfdii** [comment]
I won't be there, but @kaizhe from the Falco team will be!

**Comment by lumjjb** [comment]
Awesome - let's try to meet up, we seem to have a small enough group so that we don't really need reservations, so we can do things on the fly.

**Comment by lumjjb** [comment]
I'm guessing Tuesday evening or Wednesday lunch would be a good time (given that they moved up the entire agenda).

**Comment by dankohn** [comment]
Tuesday evening, you could meet before or after the booth crawl:

https://kccncosschn19eng.sched.com/event/PVam/welcome-reception-sponsor-showcase

Wednesday, everyone has to leave the convention center by 12:40, so you would be better off to meet for lunch at the Intercontinental Expo.

**Comment by lumjjb** [comment]
Let's meet after the booth crawl on Tuesday then. It starts at 18:50, so let's meet at 19:45. We can meet just outside the booth crawl area in the convention center and go from there. We'll coordinate by slack then.

**Comment by Kaizhe** [comment]
I will be there

**Comment by lumjjb** [comment]
Theres a mall close by, so we can meet up and walk there. 

Let's meet at the registration area at the corner facing the keynote sessions room at 1945.

**Comment by lumjjb** [comment]
The regular exit is blocked off. I am at the exit where we are being diverted to(around the Google cloud booth)

**Comment by lumjjb** [comment]
Was awesome meeting up! Closing this issue and adding it to main page archive.
