### ISSUE TITLE
[Suggestion] new members page

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#226]
Description: what's a good way for a new member to get involved?

Impact: get people doing stuff sooner, increasing impact of the group

Scope: ~1 hour -- 30 mins writing initial PR and responding to feedback

**Comment by manohar9999** [comment]
Will work on this.

**Comment by manohar9999** [comment]
@ultrasaurus can you please take a look and let me know your thoughts?

## New Members

New members are advised to:

* Join the slack group and introduce yourself.
* Regularly join the meeting atleast for the first couple of months to get yourself upto speed.
* Go through the docs in the repo. 
* Keep an eye out for `help wanted` labels in issues.  

Peer support:

* Every new member will be assigned a buddy preferably in the same time zone.
* The buddy will help in identifying the new member's areas of interest thus assigning them to the right peer group. 

Purpose of this plan:

* Ensure you become familiar with the team, know how you will contribute and what you will deliver.
* Ensure you have a clear understanding of what you will learn and deliver.

Quick links:

* TBD

**Comment by ultrasaurus** [comment]
Love this idea.  For the "buddy" program -- will need to ensure to have at least few volunteers to be buddies before we can commit to that

**Comment by garethr** [comment]
As mentioned on the call, I said I'd take a look at this.

I think the list of "advised to" things is good. It would be good to:

* Link to the Slack group in a writeup for new members. Slack "groups" are actually called channels, probably best to use the official terminology.
* Regarding "docs in the repo" I think it would be useful be be more guided here. What are the first specific three things a new member should join, irrespective of there areas of interest?
* "keep an eye out" isn't much information to go on. I think the intent here is for folks to get involved in an issue, but I think it's worth being explicit about how that works. Leave a comment on the issue? Conversation in Slack? Mention interest on the call? Different communities have different norms.

I think examples of how things typically work would be useful, probably an actual concrete example in the form of a story. So explaining how a particular issue was opening, picked up, worked on, presented back and finally closed with some action. 

Both the purpose bullets contain "become familiar/have an understanding of ... what you will deliver". Feels like this would be better rewritten to be discrete.

I think overall there are probably different types of new members, those that have engaged with SIGs or similar in adjacent or other communities, and those for whom the whole idea is new. I think the above is probably a good starting place for the former, but probably not enough for the latter group.  The Buddy program idea is probably most useful for the latter, soo it might be enough to better clarify and establish that?

Where would we look to publish this? Maybe:

* Update the README with an explicit call for new members?
* Add a new document `NEWMEMBERS.md` with a fleshed out document around the above topics?

**Comment by manohar9999** [comment]
@ultrasaurus , @garethr Here is what I have so far - 

## New Members

New members are advised to:

* Join the [CNCF Slack team](https://slack.cncf.io/), particulary [#sig-security](https://cloud-native.slack.com/messages/CDJ7MLT8S) channel and introduce yourself.
* Initially go through the following documents in the repository:
	* [README.md](https://github.com/cncf/sig-security/blob/master/README.md) 
	* [CODE-OF-CONDUCT.md](https://github.com/cncf/sig-security/blob/master/CODE-OF-CONDUCT.md)
	* [usecases.md](https://github.com/cncf/sig-security/blob/master/usecases.md)
* Regularly join the [Zoom meeting](https://github.com/cncf/sig-security/blob/master/README.md#meeting-time) atleast for the first couple of months to get yourself upto speed. 
* Here are multiple ways to get involved:
	* Join the meeting as advised above and express your area of interest or an issue.
	* Express your thoughts or ask questions on an issue you find interesting.
	* Choose an issue where [help is needed](https://github.com/cncf/sig-security/labels/help%20wanted) and comment on it expressing interest. 

Peer support:

* Every new member will be assigned a buddy preferably in the same time zone.
* The buddy will help in identifying the new member's areas of interest thus assigning them to the right peer group. 

Purpose of this plan:

* Ensure you become familiar with the team, know how you will contribute and what you will learn and deliver.

**Comment by manohar9999** [comment]
Also, I believe the buddy program will help both kinds of people. People will be able make the connections, ramp up quickly and bounce of ideas if needed.

**Comment by lumjjb** [comment]
Resolved by https://github.com/cncf/sig-security/pull/248
