### ISSUE TITLE
github issue template for presentation / use case

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#264]
Encourage people to submit ideas for presentations (either for themselves to present or a topic where they might not have a specific presenter in mind)

auto-tag the issue & create some boilerplate content to help people get started

**Comment by ultrasaurus** [comment]
This would kick off an event like the security day (not removing the need for the CFP, rather a pre-cursor to making that happen to assist in getting feedback / volunteers to help), and also for people suggesting presentations for the regular SIG meetings (like [these issues](https://github.com/cncf/sig-security/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ausecase-presentation+))

**Comment by ultrasaurus** [comment]
oops -- merged template doesn't work.  Didn't realize there was a character limit on the "about"

![image](https://user-images.githubusercontent.com/41906/68998540-52620d00-0868-11ea-851f-844136e5e762.png)

**Comment by ultrasaurus** [comment]
suggestions that fit into 200 characters

Have something you want to share with the group? Or someone you would like to invite to speak? Propose a presentation for the SIG-Security weekly meetings. 

or

Have something you want to share with the group? Or someone you would like to invite to speak? We welcome any topic related to our mission and charter.  Typical topics: projects, real-world use-cases, challenges or success stories

**Comment by lumjjb** [comment]
I like the shorter one, and maybe we can put some details into the body of the template as a comment.

**Comment by lumjjb** [comment]
Resolved by https://github.com/cncf/sig-security/pull/295
