### ISSUE TITLE
[Suggestion] Rework how we do Check-ins

### ISSUE THREAD

**Issue by MVrachev** [cncf/sig-security#265]
Description: What's your idea?

During our calls, we spent relatively around 30 minutes doing Check-ins which leaves a short time for discussions.  
There are many people who don't have updates relevant to this group or are new members and just want to observe what the group does.

My suggestion is to do a Check-in from the people who have updates relevant to this group.

**Pros**: This will save us time during our meetings and will give us time to discuss more important topics.
On another hand, if you are new to the group and you are not sure that you want to join more actively this will give the comfort to listen and observe unconstrained.

**Cons**: The Check-ins are a good way to present yourself in front of the group.
If you are shy this is a good way to go out of your comfort zone. That way the Sig Security community will easier see you and recognize you as an active member in the future.
If we remove the Check-ins for people without updates for this group it may be harder for a new member to be remembered as a regular attendant and involve more actively in the future.

**Comment by JustinCappos** [comment]
I think this is a nice suggestion.  These are valuable, but perhaps a little much the way they are being done.  Certainly, we should do something a little differently I think.

Perhaps an alternative / added suggestion is to have a check in from everyone once a month instead.  Then this can be a once every 4-5 week item instead of every week having this take about half the meeting...

**Comment by lumjjb** [comment]
I like the idea of scaling down a bit on the time for check-ins each meeting. Or perhaps we could do some simple check-in sharding :). 

I really like the new member check-ins each week, I think that really helps new members engaged and usually provides some interesting discussion points or future agenda items for the group. So i like the idea of scaling down the usual check-ins, but keeping some time (maybe 5-10 mins) for new member check-ins each week.

**Comment by MVrachev** [comment]
> I really like the new member check-ins each week, I think that really helps new members engaged and usually provides some interesting discussion points or future agenda items for the group.

I agree there is a lot of value in those check-ins but the way we do it is not optimized.

> So i like the idea of scaling down the usual check-ins, but keeping some time (maybe 5-10 mins) for new member check-ins each week.

The big question is how we practically do that. You don't what to give the word to the 10 fastest members.=

Maybe a good approach will be to give the word to the people who:
1. have updates related to the group
2. are new to the group AND have not introduced themselves already.

Of course, you could have a situation where both two requirements are met which is even better. 

@dshaw @ultrasaurus @pragashj  what do you think?

**Comment by lumjjb** [comment]
This doesn't seem to be quite the issue now with the "no-updates" and "new" indicators, i will close this and please re-open if you'd like to continue the discussion.
