### ISSUE TITLE
[Proposal] Re-organize github landing page

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#271]
>Description: what's your idea? 

Reorganize the github landing page (README.md) to have more often used information more accessible and add pointers to new comers to the new members page. 

One example of a change is would be moving the communication section up (right now the meeting link is only available after scrolling past the members list). 

>Impact: Describe the customer impact of the problem. Who will this help?  How will it help them?

This will help new members more easily find meeting times, and easier access to meeting google doc/zoom links for existing members. 

>Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" for initial proposals.  Feel free to include proposed tasks below or link a Google doc 

Not too much effort, just some reorganization of the page, adding a contents page, and moving certain items to other documents and linking to them instead. I will open a PR for this. I would like to get some feedback on what people find useful in the landing page. - or items that they usually take some time to navigate to.

**Comment by izgeri** [comment]
Some suggestions from the 9/18 SIG meeting:
- Add a TOC to the top of the document with links to the sections below (it can be literally just a bulleted list with links to sections of the page)
- Clean up view of meeting index - if it's valuable to keep a link per-meeting (to provide visibility to historic meeting schedules), we could either
  - Update the README to link to current doc only, but keep historical meeting links in a separate doc (linked to from the README) 
  - Make meeting index collapsible - this would enable us to keep it in the README but declutter the view. For example:
    <p></p>
    <details>
      <summary>Collapsed section</summary>
       <p>With a bunch of collapsed info that I'm not sure will work in an issue comment sub-bullet</p>
    </details>
    <p></p>

I think moving the members list to another page and linking from the README would also simplify a lot.

**Comment by lumjjb** [comment]
Thanks for adding the notes from the meeting here @izgeri !
