### ISSUE TITLE
[Assessment] Falco

### ISSUE THREAD

**Issue by rficcaglia** [cncf/sig-security#273]
Project Name: Falco

Github URL: https://github.com/falcosecurity/falco

Security Provider: yes

- [x] Identify team
   - [x] Project security lead: Kris Nova 
   - [x] Lead Security Reviewer: Robert Ficcaglia (@rficcaglia)
   - [x] 1 or more additional reviewer(s) - @danmx, Martin Vrachev (Observer)
   - [x] ideally 1 reviewer(s) who has used Falco in a production setting (rficcaglia)
   - [x] Declaration of reading of [security reviewer guidelines](/assessments/guide/security-reviewer.md) and declaration of conflicts (by each reviewer)
     - [x] @rficcaglia 
     - [x] @danmx 
     - [x] @MVrachev 
   - [x] Sign off by 2 chairs on reviewer conflicts
- [x] Create slack channel:  #sec-assessment-falco
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md)
- [x] Schedule Kick-Off Slack Chat
- [ ] "Dumb question phase" Lead Security Reviewer asks clarifying questions 
  - [ ] DQ1: How to scope boundaries for threat model between Sysdig core and Falco as they seem highly coupled?
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by MVrachev** [comment]
Could you please write in this issue when we have a clear starting date of the assessment?
Thank you! :))

**Comment by danmx** [comment]
Just a reminder, I wanted to volunteer to help with the assessment

**Comment by rficcaglia** [comment]
> Could you please write in this issue when we have a clear starting date of the assessment?
> Thank you! :))

I am tracking https://github.com/falcosecurity/falco/issues/807

**Comment by rficcaglia** [comment]
I promised to map CII "tasks"/requirements to sig-security assessment tasks, specifically for Falco, so here is first pass: https://docs.google.com/spreadsheets/d/1ybJ6Q7dqG7n48_k1n9d0APn41Pp3_vXMp4nzZhItwOM/edit?usp=sharing

**Comment by ultrasaurus** [comment]
Assigned to @rficcaglia -- pls confirm that this mean you can edit the issue.  We need one more volunteer!   Based on prior assessments, it would be great if we could find someone from the community who has *used* Falco and who could participate, which may or may not be the same person as security reviewer #2.

**Comment by rficcaglia** [comment]
@ultrasaurus I cannot assign or change the project or milestone attributes.  so while I can "edit" the content, I can't edit in terms of github workflow. I probably need higher level github perms.

**Comment by JustinCappos** [comment]
We're excited to have this kick off now that the incubation rush is over.  Can I get confirmation from the team that they are ready?  I noticed the slack channel was created so checked the box above.

**Comment by rficcaglia** [comment]
Kris, can you advise on readiness?

**Comment by MVrachev** [comment]
I was accepted as an "Observer" volunteer (if I understood right the Dan Shaw comment which I paraphrased here: https://github.com/cncf/sig-security/issues/256#issuecomment-534542332) in the Falco assessment and I am ready.

**Comment by danmx** [comment]
I'm still available for the assessment

**Comment by kris-nova** [comment]
Can we look at getting this done early 2020? I am happy to take lead on this, but we won't be ready to get started until the new year. 

Who would be the best folks to work with on this?

**Comment by rficcaglia** [comment]
Hi Kris!

Yes I'm happy to work with you on a Jan/Feb completion.  Between Martin,
Daniel and me, we should be able to crank through this!  Also if we can get
it done on that timeline, it would be great to present/discuss results at
Amsterdam KubeCon.

Let me know a couple dates/times for a kickoff Slack chat and let's see if
we can find one that fits everyone's time zone.

**Comment by kris-nova** [comment]
If you could drop something on my calendar nova@sysdig.com the first week of January that works for me :) 

Thanks!

**Comment by rficcaglia** [comment]
For the process, my conflict statement:

Hard conflicts:
Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project -NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:
Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - YES (I think that's a positive?)
Reviewer has contributed to the project. - NO
Reviewer has a personal stake in the project (personal relationships, etc.) - NO (though I like Michael and Kris so far ;) )

**Comment by kris-nova** [comment]
Thanks for sending this over - and we like you too!

**Comment by rficcaglia** [comment]
@danmx @MVrachev can you add your conflict statements here? Thanks!

**Comment by rficcaglia** [comment]
@kris-nova here is the [OPA self-assessment](https://github.com/cncf/sig-security/blob/master/assessments/projects/opa/self-assessment.md) and the ["official" outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md).

**Comment by danmx** [comment]
@rficcaglia, my conflict statement: 
- Hard conflicts:
    - Reviewer is a maintainer of the project - NO
    - Reviewer is a direct report of/to a maintainer of the project - NO
    - Reviewer is paid to work on the project - NO
    - Reviewer has significant financial interest directly tied to success of the project - NO

- Soft conflicts:
    - Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
    - Reviewer uses the project in his/her work - semi-YES (not yet but I'm going to start using it this quarter)
    - Reviewer has contributed to the project. - NO
    - Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by MVrachev** [comment]
My conflict statement:

Hard conflicts:
Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project -NO
Reviewer has significant financial interest directly tied to the success of the project - NO

Soft conflicts:
Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by JustinCappos** [comment]
@ultrasaurus @pragashj @dshaw Need conflict signoff from 2 chairs...

**Comment by JustinCappos** [comment]
I'm signing off as their being no conflicts.  We're ready for the self assessment!

**Comment by ficcaglia** [comment]
@kris-nova can you confirm if you should still be assigned the project lead?

**Comment by JustinCappos** [comment]
Inactive.  Closing and removing from queue
