### ISSUE TITLE
KubeCon + CloudNativeCon, Shanghai , Nov 14-15, 2018

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#28]
[KubeCon + CloudNativeCon , Shanghai](https://www.lfasiallc.com/events/kubecon-cloudnativecon-china-2018/)

Nov 14-15, 2018

Who is going?  anyone want to help organize an in-person meeting?

[Call for Proposals](https://www.lfasiallc.com/events/kubecon-cloudnativecon-china-2018/program/call-for-proposals-cfp/) Close: July 6, 2018

**Comment by rae42** [comment]
I'm doing a Bird of a Feather talk titled "Access policies for hybrid cloud environments".
Description: A typical admin/developer today needs to deal with many access policy systems: K8S RBAC, Istio RBAC and ABAC, OPA, policies from cloud vendors including IAM, firewall rules, quota etc. Reasoning about access across these systems is getting more and more complex and difficult. We want to invite those who build access policies and those who use access policies to come together to discuss the vision of a secure, easy to use and consistent/coherent access management experience across infrastructure, services and applications. And more importantly: how do we get there?

**Comment by lumjjb** [comment]
Past event - inactive.
