### ISSUE TITLE
[Suggestion] Help introducing a security feature in K8s: Support node-level user namespace remapping

### ISSUE THREAD

**Issue by danmx** [cncf/sig-security#282]
[User namespace](http://man7.org/linux/man-pages/man7/user_namespaces.7.html) remapping is a way to prevent privilege-escalation attacks from within a container is to configure your container’s applications to run as unprivileged users. For containers whose processes must run as the `root` user within the container, you can re-map this user to a less-privileged user on the host.

[Docker](https://docs.docker.com/engine/security/userns-remap/) container runtime supports user namespace remapping.

In 2016 there was an [enhancement issue](https://github.com/kubernetes/enhancements/issues/127) opened to support it in Kubernetes.
In 2018 a [proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-usernamespace-remapping.md) was created.

As of today this enhancement is still pending inclusion to k8s version 1.17.

I think that as Security SIG we should help this feature be adopted.

Impact: In many cases container still ran as `root` user which maps to `root` host user. This feature will greatly increase security and even more if it'll become a default setting. 

Scope: not yet determined

Additional info:
- [enhancement issue](https://github.com/kubernetes/enhancements/issues/127)
- [proposal](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-usernamespace-remapping.md)
- [Docker runtime user namespace remapping functionality](https://docs.docker.com/engine/security/userns-remap/)

**Comment by justincormack** [comment]
The feature needs implementing, rather than help adopting. There are also significant barriers to implementation around mounts; currently Ubuntu is patching their kernel with shiftfs support, as this is not upstream in Linux. Note also that you get the same security by simply not running your container as root, user namespaces are only needed for some use cases where you need to also provide partial root privileges to a container.

**Comment by danmx** [comment]
I found cases in different organizations where it was hard to enforce `non-root` users and having such feature (especially by default) would reduce the risk. 
I wasn't aware of technical limitation of upstream Linux. Thank you, I'll dig deeper and read more about it.

**Comment by lumjjb** [comment]
I will close this issue since there are follow-up steps required before we can talk about this.. @danmx , do feel free to re-open this when implementation is ready!
