### ISSUE TITLE
KubeCon + CloudNativeCon, North America, Dec 11-13, 2018

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#29]
[KubeCon + CloudNativeCon, North America](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2018/)

December 11 - 13, 2018
Washington Convention Center
Seattle, WA

[Call for Proposals](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2018/program/call-for-proposals-cfp/) Close: August 12, 2018

**Comment by qnetter** [comment]
I will be attending and would like to attend a meetup.

**Comment by andrei821** [comment]
Just had a great discussion in SHANGHAI with Liz - Will be attending to NA as well.

**Comment by lumjjb** [comment]
Past event - inactive.
