### ISSUE TITLE
KubeCon + CloudNativeCon, San Diego, USA - Nov 18 - 21, 2019

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#290]
KubeCon + CloudNativeCon, San Diego, USA - Nov 18 - 21, 2019

San Diego Convention Center
111 W Harbor Drive
San Diego, CA 92101

Let's meet up in person!

**Comment by ashutosh-narkar** [comment]
+1 for Tuesday dinner.

**Comment by lumjjb** [comment]
Upvote @ashutosh-narkar 's comment if Tuesday works! We will most likely meet at conference venue and find a place from there. Anyone familiar with the SD area have recommendations?

**Comment by lumjjb** [comment]
Let's move this conversation to: https://github.com/cncf/sig-security/issues/128.. Realized this is a duplicate issue.
