### ISSUE TITLE
[Proposal] Adjustments to Supply Chain Compromise

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/sig-security#298]
Description: The type of compromise area for supply chain compromise listing has attacks mixed in with categorization of compromise.  Further, several attacks list multiple steps but could potentially just be updated to enumerate all the compromise types that occurred.

Impact: Clearer understanding of what a compromise is.  Provide standardization in the types of compromise associated with incidents.

Scope: Re-evaluation and updates of the listing

Additional info:
- I'm currently working on the definitions for the types of compromise and reviewing the listing led to confusion.

**Comment by lumjjb** [comment]
@TheFoxAtWork you mentioned that you're currently working on this - should I make it a proposal instead?

**Comment by TheFoxAtWork** [comment]
Yes - we're currently working on this.

**Comment by TheFoxAtWork** [comment]
here is the PR for it (at least the start of the work) https://github.com/cncf/sig-security/pull/304

**Comment by ultrasaurus** [comment]
assigned to @TheFoxAtWork

**Comment by ultrasaurus** [comment]
PR merged, closing this.  Thank you @TheFoxAtWork  !
