### ISSUE TITLE
[Assessment] CNCF sandbox project Dragonfly

### ISSUE THREAD

**Issue by allencloud** [cncf/sig-security#302]
Project Name: Dragonfly

Description: Dragonfly is an intelligent P2P based image and file distribution system.

Github URL: https://github.com/dragonflyoss/Dragonfly

Security Provider: no

- [ ] Identify team
   - [x] Project security lead (Allen Sun)
   - [ ] Lead Security Reviewer
   - [x] 1 or more additional reviewer(s) @JustinCappos 
   - [ ] Declaration of reading of [security reviewer guidelines](/assessments/guide/security-reviewer.md) and declaration of conflits (by each reviewer)
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [x] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md)
- [ ] "Dumb question phase" Lead Security Reviewer asks clarifying questions 
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by JustinCappos** [comment]
Assuming this is prioritized by the TOC, who would like to lead the assessment?  Can we get someone who has not already done so?

I volunteer to participate as a reviewer.

**Comment by ultrasaurus** [comment]
@allencloud are you involved with the project and volunteering as (or able to find) the person who would act as [project lead](https://github.com/cncf/sig-security/blob/master/assessments/guide/project-lead.md) or is this a project you are using (or want to be using) and are interested in the output of the security assessment?  or ...?

**Comment by allencloud** [comment]
@ultrasaurus 
I am one the Dragonfly maintainers and act as the project lead. We are trying to promote Dragonfly project from Sandbox level to Incubation level. The chapter says that we had better to have security assessment help from SIG secrurity.

**Comment by allencloud** [comment]
That could not be better.  @JustinCappos Thank you. ❤️

**Comment by JustinCappos** [comment]
I created the slack channel ( #sec-assessment-dragonfly) on the CNCF slack, but don't know your name to invite you, @allencloud .  Please join and invite others who may be involved to do so as well.

**Comment by lizrice** [comment]
@dshaw @ultrasaurus  @pragashj this is currently marked as inactive, can we reactivate it please?

**Comment by JustinCappos** [comment]
This has been inactive long enough that I'm closing.  Please open a new issue when your team wants an assessment, @allencloud
