### ISSUE TITLE
[Proposal] Add CODEOWNERS file for automatic review request

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#303]
Description: what's your idea? 

Adding CODEOWNERS file to specific directories which should require reviews by the owner of the sub folder. i.e. assessments owner should be the assessment facilitator, etc.

Impact: Describe the customer impact of the problem. Who will this help?  How will it help them?

This will help the management and governance of the repository.

Scope: Probably a couple of days if no additional tweaks to github permissions is required.

TO DO
- [x] SIG Representative (@ultrasaurus)
- [x] Project leader(s) (@lumjjb)

Tasks
- [x] Create Initial CODEOWNERS template
- [x] Create list of sub-directories that should have CODEOWNERS files based on CONTRIBUTING.md and /governance (https://github.com/cncf/sig-security/pull/330/files)
- [x] submit separate PRs for each sub-directory with approval of at least one chair and at least one person named in the file (for both review & awareness)
- [x] Switch on CODEOWNERS review requirement on master branch

**Comment by ultrasaurus** [comment]
This sounds like a great improvement

Maybe add TODO to the proposal?  suggestions:

- create list of sub-directories that should have [CODEOWNERS](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) files based on CONTRIBUTING.md and /governance
- submit separate PRs for each sub-directory with approval of at least one chair and at least one person named in the file (for both review & awareness)

**Comment by lumjjb** [comment]
Completed
