### ISSUE TITLE
[Assessment] SPIFFE/SPIRE

### ISSUE THREAD

**Issue by evan2645** [cncf/sig-security#308]
Project Name: SPIFFE/SPIRE

Github URL: https://github.com/spiffe/spire

Security Provider: yes

- [x] Identify team
   - [x] Project security lead (Evan Gilman)
   - [x] Lead Security Reviewer (Brandon Lum)
   - [x] 1 or more additional reviewer(s) (Justin Cappos, Emily Fox)
   - [x] Declaration of reading of [security reviewer guidelines](https://github.com/cncf/sig-security/blob/master/assessments/guide/security-reviewer.md) and declaration of conflits (by each reviewer)
   - [x] Sign off by 2 chairs on reviewer conflicts (Justin Cappos in lieu of chairs who are preoccupied)
- [x] Create slack channel (e.g. #sec-assess-projectname)
- [x] Project lead provides draft document  [outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md) -- [self-assessment](https://docs.google.com/document/d/1PCTrSSpM62S8WLLocb7_UU4XtoHLROp-Q92ZpfLBgeA/edit)
- [x] "Dumb question phase" Lead Security Reviewer asks clarifying questions 
- [x] Initial review
- [x] Presentation & discussion (Done on 26 Feb)
- [x] Share draft findings with project
- [x] Assessment summary and doc checked into /assessments/projects/project-name
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by lumjjb** [comment]
I am willing to volunteer be a security reviewer for this assessment, and am able to lead.

**Comment by JustinCappos** [comment]
Context: I did the "assessment" before for the project before there was a
SIG-Security process.

I'm happy to participate in this one as well and would be happy for Brandon
to lead.  :)

**Comment by lumjjb** [comment]
Link issue for previous assessment by @JustinCappos https://github.com/cncf/sig-security/issues/97

**Comment by JustinCappos** [comment]
Here is the project's self assessment:  https://docs.google.com/document/d/1PCTrSSpM62S8WLLocb7_UU4XtoHLROp-Q92ZpfLBgeA/edit

**Comment by lumjjb** [comment]
Conflict declaration: No conflicts with this project.

**Comment by JustinCappos** [comment]
No conflict from my side either.  I like the folks there a lot, but not in a way that would impact my objectivity in a security assessment.  :)

**Comment by TheFoxAtWork** [comment]
Happy to help, no conflicts - no experience as lead assessor but will help anyway i can

**Comment by JustinCappos** [comment]
@TheFoxAtWork volunteered as well!

**Comment by evan2645** [comment]
👋 hi everyone! Sorry I'm late to the party :)

I made some minor updates to the self assessment today, but nothing major - I think @anvega did a pretty thorough job (thanks Andres!!). We have removed the `Draft` label that previously appeared in the document name.

One thing that probably needs some attention is that the previous assessment (the results of which are in the self assessment) did not account for "Evil Server / Victim Server" attack vector. There may also be a modifier there of "Same Trust Domain" and "Different Trust Domain". I'm not sure if the old assessment methodology applies to the new process.

**Comment by JustinCappos** [comment]
We're doing a lighter process here (no collusion matrices for most projects).  I think we might have still taken a few steps down this path here because the setup and trust relationships are fairly complex.

**Comment by lumjjb** [comment]
Here is the proposed schedule. How does this look like for all? 

Jan 6-10: "Dumb questions phase" 
(only project lead (and team) + lead security reviewer involved)

Jan 13 - 22: Security review phase - security reviewers add comments on the doc and conversation around edits to the doc continues
(project lead (and team) + all security reviewers)

Jan 22: Presentation to SIG-security meeting 
(at least 1 representative from project team and security reviewers)

By Jan 24: Address all remaining comments, and finalize TOC summary (1 slide)

(To be scheduled) 1 slide sharing to the TOC

**Comment by JustinCappos** [comment]
I've read the reviewer guidelines.

**Comment by JustinCappos** [comment]
> Here is the proposed schedule. How does this look like for all?
> 
> Jan 6-10: "Dumb questions phase"
> (only project lead (and team) + lead security reviewer involved)
> 
> Jan 13 - 22: Security review phase - security reviewers add comments on the doc and conversation around edits to the doc continues
> (project lead (and team) + all security reviewers)
> 
> Jan 22: Presentation to SIG-security meeting
> (at least 1 representative from project team and security reviewers)
> 
> By Jan 24: Address all remaining comments, and finalize TOC summary (1 slide)
> 
> (To be scheduled) 1 slide sharing to the TOC

@evan2645 Does this timeline work for you?

**Comment by lumjjb** [comment]
I've read reviewer guidelines

**Comment by lumjjb** [comment]
@ultrasaurus @dshaw @pragashj require 2 co-chairs on reviewer conflicts

**Comment by lumjjb** [comment]
Note, as per discussion on slack, the initial "Dumb Question Phase" is not a full time commitment but more of an asynchronous process. I've allocated a bit of a buffer due to 18 hour timezone difference between myself and Evan, and my travel from SIN->SFO on 9-10 Jan.

**Comment by ultrasaurus** [comment]
@lumjjb it looks like there are no reviewer conflicts, so we don't need chair review -- or did I miss something?

**Comment by anvega** [comment]
@ultrasaurus Wording may need to be revised. We interpreted the checkbox item as 2 SIG-chairs asserting that there are no reviewer conflicts and not a signoff where a conflict exists.

**Comment by evan2645** [comment]
@JustinCappos Sure, I think that will work OK. I'm not traveling over the holiday season so am free to start whenever, but of course I understand that I'm probably the outlier :-D

One thing I will note is that I will probably be unavailable from Jan ~8-19th. I have spoken to @azdagron about this though, and he is willing to cover and help answer any questions in my absence as I'm not sure what my internet access will look like during that time. @azdagron is a SPIRE maintainer.

**Comment by lumjjb** [comment]
@evan2645 yep that is fine. 

@TheFoxAtWork how does schedule look for you?

**Comment by TheFoxAtWork** [comment]
yep yep works for me @lumjjb

**Comment by JustinCappos** [comment]
@ultrasaurus @dshaw @pragashj Can we get the chair signoff so we can move this to completed?

I think this means that @TheFoxAtWork @lumjjb and me need to submit our conflict forms as well...

**Comment by JustinCappos** [comment]
Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NOT REALLY.  I performed a security audit / assessment of the project previously.
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by anvega** [comment]
@JustinCappos Its been some time since the assessment was merged. I heard mention of this during today's SIG-Security call. Is there anything needed to close this issue and mark it done?

**Comment by JustinCappos** [comment]
> @JustinCappos It’s been some time since the assessment was merged. I heard mention of this during today's SIG-Security call. Is there anything needed to close this issue and mark it done?

I think we're just waiting on the administrative items below from the SIG-Security side.  Let's give people a day or two, but it should be closed this week.

> @ultrasaurus @dshaw @pragashj Can we get the chair signoff so we can move this to completed?
> 
> I think this means that @TheFoxAtWork @lumjjb and me need to submit our conflict forms as well...

**Comment by JustinCappos** [comment]
Okay, given the chairs are preoccupied.  I'm signing off on the COI.

**Comment by kapilt** [comment]
The self-assessment doc here isn't accessible anymore

**Comment by lumjjb** [comment]
The assessment doc is now part of the repo as an `.md` file: https://github.com/cncf/sig-security/blob/master/assessments/projects/spiffe-spire/self-assessment.md
