### ISSUE TITLE
Is the assessment matrix duplicative with the issue process for assessments?

### ISSUE THREAD

**Issue by JustinCappos** [cncf/sig-security#309]
It feels like the assessment matrix: https://github.com/cncf/sig-security/blob/8f02ab936dd1ec05405ca995221b601c5a7382ca/assessments/assessment-matrix.md
is largely duplicative with the tagged items in the issue tracker:  https://github.com/cncf/sig-security/labels/assessment

Do we need both?  If so, could we generate from the other (likely issue -> matrix)?

**Comment by ultrasaurus** [comment]
see related discussion "Assessments Listing" (issue https://github.com/cncf/sig-security/issues/206)

I think the [current matrix](https://github.com/cncf/sig-security/blob/8f02ab936dd1ec05405ca995221b601c5a7382ca/assessments/assessment-matrix.md) could be simplified to be a priority queue, addressing the remaining open issue in the "intake process" PR (https://github.com/cncf/sig-security/pull/296)

**Comment by ultrasaurus** [comment]
What about if we made a github "project" for assessments?  it would be easier to maintain the order of the queue (since it seems the start of an assessment is often delayed due to self-assessment not being ready)

**Comment by JustinCappos** [comment]
> What about if we made a github "project" for assessments? it would be easier to maintain the order of the queue (since it seems the start of an assessment is often delayed due to self-assessment not being ready)

I'm not 100% sure what you mean.  Is the purpose of the project to give a template for self-assessment?  What is it for?

**Comment by ultrasaurus** [comment]
I created a TEST project to illustrate: https://github.com/cncf/sig-security/projects/2

**Comment by JustinCappos** [comment]
I created the need-self-assessment label to help us track.  Looks like we can close this!

**Comment by ultrasaurus** [comment]
I think we can remove the [assessment matrix](https://github.com/cncf/sig-security/blob/8f02ab936dd1ec05405ca995221b601c5a7382ca/assessments/assessment-matrix.md) page then

**Comment by lumjjb** [comment]
I love the new project board! :)

**Comment by JustinCappos** [comment]
Great!  After #310 is approved and merged, we can close this issue then...
