### ISSUE TITLE
[Suggestion] System for meeting times to make it friendly to other timezones

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#312]
Description: 

Propose a system to set meeting timings so they are accessible to a members across different timezones. 

Impact: 

This will help engage the greater community and provide more opportunities for inclusiveness to current timezones where meeting times are not convenient (i.e. Asia, Australia, etc.)

Scope: "not yet determined" 

Additional info:
- Reference to supporting material
- Links to related site
- Feel free to delete this section if you don't have more info

**Comment by lumjjb** [comment]
notes from meeting on 19 Dec 2019:

Meeting time rotation suggestion
- This time not very convenient for the East like folks in Asia
- Suggestion: Sync with the KubeCon timezone a month before and a couple of months after

**Comment by pragashj** [comment]
@lumjjb can you have done proposals to discuss with the team and also content document here in this issue for others to chime in.
Cc/ @hannibalhuang

**Comment by ultrasaurus** [comment]
11p would be more friendly to China and less so for US (except for the west coast night owls) -- though maybe midnight Pacific / 8a GMT is easier for EU.

![image](https://user-images.githubusercontent.com/41906/73763468-49c1fa00-4726-11ea-85f4-4877c99690bf.png)

March 30 – April 2 [CloudNativeCon EU](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/)
July 28-30 [CloudNativeCon / KubeCon China](https://www.lfasiallc.cn/kubecon-cloudnativecon-open-source-summit-china/)

**Comment by lumjjb** [comment]
- Additional meetings per month to keep momentum (i.e. once a month like SIG docs)
- Eventual idea of federation across regions
- Projects specific to region, leadership locally bootstrap with facilitators

**Comment by AkihiroSuda** [comment]
Simple question: why does CNCF (not just SIG-security) need synchronous communication at all?

**Comment by lumjjb** [comment]
Close from inactivity

**Comment by pragashj** [comment]
@JustinCappos now that you are in the chine timezone, can you workout a proposal for this -- one person that could be of help here is @hannibalhuang

**Comment by JustinCappos** [comment]
> @JustinCappos now that you are in the chine timezone, can you workout a proposal for this -- one person that could be of help here is @hannibalhuang

From what I understand, this is mostly just setting up a meeting structure that mirrors the other SIG Security meeting, but which is at a more convenient time for participants in Asia.  I'm not sure what you mean about working out a proposal.  

I don't really know how to get the word out to the right folks.  Thoughts on this?

**Comment by pragashj** [comment]
Monday/Tuesday Feb, 15/16 2021 -- first kick-off meeting happened and the meeting times are updated on the readme. Closing this issue for now if @lumjjb @ultrasaurus and @TheFoxAtWork are good with this.

**Comment by ultrasaurus** [comment]
pls link in the PR -- which I think is already merge, I think it addresses this issue

**Comment by pragashj** [comment]
This https://github.com/cncf/sig-security/pull/529 addresses this issue, closing the issue.
