### ISSUE TITLE
[Suggestion] Automate scribe process via cloud tool(s)

### ISSUE THREAD

**Issue by rficcaglia** [cncf/sig-security#314]
Description: What's your idea?
Something like AWS Transcribe or Google Speech, something that is automated. 

Impact: Saves volunteer effort and time spent asking "who can be a scribe"?

Scope: How much effort will this take? 
mostly discovery ( a few hours?) then if we find a tool that needs some scripting/infrastructure spec'ing that out.

Additional info:
None

**Comment by manohar9999** [comment]
@rficcaglia , @lumjjb I can help with this. Let me scope it out and get back to you with questions.

**Comment by lumjjb** [comment]
Hi @manohar9999 ! Yes! That would be awesome. Would be excited to hear what you have in mind!

**Comment by whaber** [comment]
Interesting idea.  It will be fascinating to see how accurate it is, and if the accuracy is high enough for this to replace a human scribe (or would the scribe role go from being a writer of everything to having the role be to edit/correct system decides what was said).

**Comment by yeelinglam** [comment]
@manohar9999 - this would influence #350 which I plan to work on. Could you please keep me in the loop on what you scoped out so far?

**Comment by lumjjb** [comment]
having text + the person who said it should be sufficient. The idea is that the general crux of the content be in a written form. 

Facilitators + other attendees will still be able to add links to the agenda in the meeting notes, but not as verbose as we have today. (mainly links, action items, future discussions)

**Comment by chasemp** [comment]
I was recently involved in a podcast that used https://otter.ai/login to generate transcripts and it worked surprisingly well.  It did have a bit of an issue with some words that in hindsight were not enunciated very clearly, but overall it would be very functional for a complete record across calls.  That may leave only a human denoting "action items" which would be much lighter I expect.

**Comment by timfong888** [comment]
It is possible short term and for previous Zooms to export the WebVTT file. If speakers authenticated, the speaker names show up with a running time stamp.  Linking to the export from the agenda and linking from YouTubeto the angenda doc with anchor should cover it.

**Comment by lumjjb** [comment]
we now have access to zoom transcripts which does a pretty good job of transcription, we need a way to make it accessible.. any thoughts? I'm not sure if putting it directly into the repo may be good since it will inflate the size of the repo. Does anyone have suggestions?

**Comment by PushkarJ** [comment]
@lumjjb we could create a google doc extending the current meeting minutes doc or replacing it with this auto transcript and link it in meeting invite

**Comment by lumjjb** [comment]
Yea.i think a folder would be good idea, i've been running into many issues finding things in the meeting minutes doc just because its so huge... Unless there's a good way to make collapsables or something in gdocs

**Comment by lumjjb** [comment]
Actually... zoom does provide a link to the transcripts... If people are able to access this, we can also just copy the link to the meeting minutes

https://zoom.us/rec/sdownload/BQ6YVnpTgrC5M46jKjlchHhdWixppTIJAXo19J9VApYB3SJBd-mkj8diauROiAP76Vx4otW6wq_NebFW.SlHenuZ1-yjANm8-

**Comment by TheFoxAtWork** [comment]
Closing this issue.  Transcripts are available but not readily automated for linking/posting in the repo.
