### ISSUE TITLE
[Presentation]  Threat Modeling in FSS and Open Source Simulation Training materials 

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#332]
Title:  Threat Modeling in FSS and Open Source Simulation Training materials 

Speakers: Jonathan Meadows, Andrew Martin

Description: 

- Which controls should be applied to Kubernetes
- Skills gap - need to train security engineers in Kube
- Controls
  - Looking at threat modeling
  - What kind of attacks can be used
  - Focusing on how to automate regression testing and validate thread model
  - Trying to develop methods to demonstrate threats being identified
  - Able to show how an attacker get into a system and teach the security teams how the attackers are doing it.

... More details in meeting minutes: https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.mltwmtabtgwk

Time: 30 mins

Availability: 22 Jan 2019

- [x] SIG Representative
- [x] Schedule date: 22 Jan 2019

**Comment by lumjjb** [comment]
@jonmuk @sublimino

**Comment by jonmuk** [comment]
Thanks for the invite to present our work from the FSUG.  I look forward to continuing the conversation on automating the model and our next focus areas which are securing the supply chain and codifying controls.

[FSUG - Threat Modelling & Kubernetes Security Training](https://github.com/cncf/financial-user-group/blob/master/projects/k8s-threat-model/Threat%20Modelling%20%26%20Kubernetes%20Security%20Training%20-%20Jon%20Meadows%20and%20Andrew%20Martin%2C%20sig-security%20_%20Financial%20Services%20User%20Group%2C%20CNCF%20(22nd%20Jan%202020).pdf)

**Comment by lumjjb** [comment]
Completed Presentation
