### ISSUE TITLE
[Suggestion] Add recommendations for tooling in security assessments

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#335]
Description: During the security assessments, there are some steps, like taking the self-assessment (that usually comes in a google doc form for collaboration), and make it into a markdown format for the repo.

Impact:  This will help lead security reviewers in performing security assessments

Scope: After discussions, should be a short 10 min task to add a line to include tooling.

**Comment by lumjjb** [comment]
@ultrasaurus

**Comment by lumjjb** [comment]
I used https://pandoc.org/ for the SPIRE review self-assessment conversion (downloading a docx and then converting it).

**Comment by JustinCappos** [comment]
I'm open to this but don't know the tools well enough to say more than "this sounds like a good idea".  

@lumjjb Do you want to have a PR where you suggest Pandoc, while leaving it open for people to choose what they like?

**Comment by lumjjb** [comment]
Yea i was going to open a PR, but i think @ultrasaurus also had some recommendations to add. So I'd consolidate them and add them to the guide.

Yea - agree on it being just a suggestion.

**Comment by lumjjb** [comment]
Resolved by https://github.com/cncf/sig-security/pull/336
