### ISSUE TITLE
SIG- Security Meeting RSA Week ( Between 2/23-2/28)

### ISSUE THREAD

**Issue by piyushcom** [cncf/sig-security#340]
Folks -
if you are travelling to SF for RSA or you are in the city that week, we can organize an event for SIG -security community. Let me know the thoughts.

**Comment by lumjjb** [comment]
Hi @piyushcom !  Thanks for opening the issue. Hope a meetup can happen.

Could you edit the title to include the date of the event and city? Thanks!

**Comment by piyushcom** [comment]
I am creating the event on eventbrite , i would need to know how many are available.

**Comment by IAXES** [comment]
@piyushcom Good day,
  
Has this event concluded? If so, could I please request a link to slides/recordings/summaries (if available). After that point, I'll request the issue be closed, if there are no objections.
