### ISSUE TITLE
[Presentation] Cartography - Using Graphs to Improve and Scale Security Decision-Making

### ISSUE THREAD

**Issue by achantavy** [cncf/sig-security#347]
## Title: What is the title of your presentation?

Cartography - Using Graphs to Improve and Scale Security Decision-Making

## Speakers:

Alex Chantavy (@achantavy)

## Description:

Cartography is a Python tool that consolidates infrastructure assets from multiple sources and the relationships between them in an intuitive graph view powered by a Neo4j database.  It is particularly good at exposing non-obvious or otherwise hidden dependency relationships between nodes so that service owners may validate assumptions about security risks.

Cartography is not the only OSS security graph tool out there, but it differentiates itself by being fully-featured yet generic and extensible enough to help make anyone better understand their risk exposure, regardless of what platforms they use.  Rather than being focused on one core scenario or attack vector, Cartography focuses on flexibility and exploration.

https://github.com/lyft/cartography

At this time, we aren't necessarily looking to join the foundation but we would love to get project feedback for potential eventual submission.

## Time: How long will the presentation take? (estimate)

30m

## TO DO

- [X] SIG Representative @lumjjb 
- [X] Schedule date: 03/11/2020

**Comment by achantavy** [comment]
CC:@mattklein123

**Comment by lumjjb** [comment]
Awesome @achantavy! This looks like a great topic. I've queued it up for 03/11.

**Comment by ultrasaurus** [comment]
@lumjjb updated issue description and assigned you as SIG representation -- feel free to recruit someone else at the meeting today to take this on (to update the issue with video when available) -- I'm out of town today so will miss, but do look forward to catching up when video is posted!

**Comment by IAXES** [comment]
@ultrasaurus Good day, 

How are meetings recorded/saved and uploaded? Does the meeting automatically record to cloud storage, or does it need to be triggered by specific individuals attending the meeting? I haven't used Zoom much, but it appears to save to local storage when I host my own meetings. Thank you.

**Comment by lumjjb** [comment]
The meetings are uploaded to the CNCF sig security youtube playlist automatically: https://www.youtube.com/watch?v=HvHRffteItQ&list=PLj6h78yzYM2MJRBYu9jUisJIXJvi-8jlp

**Comment by lumjjb** [comment]
Hi @achantavy, can you post a link to your slides here? Thanks!

**Comment by achantavy** [comment]
@lumjjb Here: https://docs.google.com/presentation/d/1pLbQbORYtF_WHl24GHY4LrQKHd7Rz9B56Tu0YICdeek/edit#slide=id.g6599e03b20_0_0 :-)

**Comment by lumjjb** [comment]
Awesome! Thanks!

**Comment by lumjjb** [comment]
This presentation is completed. Closing the issue
