### ISSUE TITLE
[Proposal] Add "scribe" role plus details to "Working group roles" document

### ISSUE THREAD

**Issue by IAXES** [cncf/sig-security#350]
Description: I'd like to add a "scribe" role plus details to the ["Working group roles" document](https://github.com/cncf/sig-security/blob/master/governance/roles.md).

Impact: Further fleshes out the roles documentation. This could be useful for members offering to volunteer as scribes during the weekly meetings.

Scope: Not much at all. The written portion would not exceed that for existing roles. I imagine proposed edits/additions in the pull request will consume more time than the initial commit.

TO DO
- [x] SIG Representative (@lumjjb)
- [x] Project leader(s)
- [ ] TBD

**Comment by TheFoxAtWork** [comment]
@lumjjb please take a look

**Comment by TheFoxAtWork** [comment]
also recommend changing it from "working group roles" to SIG Roles since we aren't SAFE WG anymore

**Comment by lumjjb** [comment]
This is a great idea to add the scribe role. I have updated to have myself as SIG rep. Looking forward to this PR!
