### ISSUE TITLE
[Proposal] Meeting agenda and minutes format updates

### ISSUE THREAD

**Issue by IAXES** [cncf/sig-security#351]
Description: I'd like to propose some changes to the [meeting notes document](https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/). In short:

1. For the "Agenda" section, I'd like to replace the bulleted lists with IEEE style numbered lists. The idea being that each agenda item has a unique, numeric, shorthand identifier.
2. For meeting minutes, the addition of a table up to ~~4~~ 3 columns wide (1x to identify the topic, such as the agenda shorthand number/name, and ~~3x~~ 2x columns for the scribes). The idea being this being that meeting minutes can be written in parallel by scribes (i.e. editing the Google doc in parallel) without stepping on each others' toes.
3. I'd also like to request feedback on (2), as this might be preferable to multiple independent sets of minutes/notes presented serially in the document, and avoids having to manually merge 2-3 sets of notes after the conclusion of the meeting. Minutes can also directly align with the associated agenda item visually.

Impact: Change could help with meetings (i.e. agenda items uniquely numbered). The column-based minutes approach could shorten the "Meeting Minutes" sections as well by condensing them and combining them with the "Agenda" section.

Scope: Implementation would be minimal. The real work would be with scribes using the setup (maybe a short demo/presentation would be in order) on an ongoing basis.

TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by IAXES** [comment]
Here's an example of what I had in mind.

![image](https://user-images.githubusercontent.com/8325672/75942997-b70d9b80-5e48-11ea-8224-7f89572c9e30.png)

**Comment by IAXES** [comment]
Seems to work for smaller notes, less so for larger items.  

https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#heading=h.rrcy1iy7m903

I'll re-create the same template for next week. If it's causing any hassle for scribes (please feel free to chime in), I'll re-use the previously established template.

**Comment by lumjjb** [comment]
@IAXES thanks for the great idea to reorganize the meeting notes. I agree that this is something that could be better - and maybe even coming up with a better scribe system in itself.

I think this does solve the synchronization problem, but as a reading of the meeting notes, I find it a bit cumbersome to read because it is not certain what order to read the notes in (moving from left to right column). If there is a way to create this separation during the meeting, but then merge these together so that they are in a single timeline, it would be perfect.

Another small note on the left column is that I feel like it does take up a lot of blank space as content starts to fill up, maybe having a header and then two columns below may make that feel a bit better.

**Comment by IAXES** [comment]
@lumjjb 

> I think this does solve the synchronization problem, but as a reading of the meeting notes, I find it a bit cumbersome to read because it is not certain what order to read the notes in (moving from left to right column). If there is a way to create this separation during the meeting, but then merge these together so that they are in a single timeline, it would be perfect.

Hmm, I could have two duplicate tables (i.e. one beneath the other) and then re-combine them after the meeting concludes. Don't know how accommodating Google docs will be for this, but I could definitely try.

> Another small note on the left column is that I feel like it does take up a lot of blank space as content starts to fill up, maybe having a header and then two columns below may make that feel a bit better.

Agreed: I'd considered that too. The easiest approach (while continuing to use Google docs) might be to change the page layout (if there are no objections) from 8.5"x11" portrait to A4 landscape (i.e. "widescreen" setup). That should make the layout easier to read and work with.

I'll investigate if there are advanced features (i.e. scripting) that are supported by Google Docs that could help improve the layout and ease-of-use for scribes.

**Comment by TheFoxAtWork** [comment]
Made adjustments to the margins, since the new table format makes this much nicer to manage.  Closing issue.

Also - may be beneficial to check out hackmd.io  ?  CC @danpopSD

**Comment by danpopSD** [comment]
recommended.  you can keep an ongoing md file and have folks update in realtime.  this is something we do in the falco community.

let me know if its something the sig wants me to help with.
