### ISSUE TITLE
[Suggestion] Documentation update - roadmap.md

### ISSUE THREAD

**Issue by IAXES** [cncf/sig-security#353]
Description: The "SAFE WG Roadmap" title should be updated to "SIG-Security Roadmap" [in the roadmap document](https://github.com/cncf/sig-security/blob/master/roadmap.md), as per [a related discussion in Slack](https://cloud-native.slack.com/archives/CDJ7MLT8S/p1583401459049600).

Impact: Minor documentation updates.

Scope: Minimal.

**Comment by TheFoxAtWork** [comment]
updated with new PR
