### ISSUE TITLE
Software Identity: Workload Identity, Service Identity, Application identity

### ISSUE THREAD

**Issue by dshaw** [cncf/sig-security#36]
Prompt from [2018-06-29 meeting](https://docs.google.com/document/d/1fyBDIm82xtTYWhZu3gyLahltMdTOxl9aWfOfRxYHapo/edit):
Software Identity: Workload Identity, Service Identity, Application identity — are these the same thing?

**Comment by dshaw** [comment]
The SPIFFE Identity and Verifiable Identity Document is focused on Workload Identity, but are still struggling to find the right expression.

https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md

**Comment by lumjjb** [comment]
Closed due to inactivity.
