### ISSUE TITLE
[Presentation] Glimpse of Security Facets of Scaled Agile (SAFe) 

### ISSUE THREAD

**Issue by knowlengr** [cncf/sig-security#360]
Title: Glimpse of Security Facets of Scaled Agile (SAFe) 

Speakers: Mark Underwood [https://github.com/knowlengr](url), Neil Sanyal [https://www.linkedin.com/in/neilsanyal/](url) VP PMO Director for Information Security (Synchrony) 
The speakers are representing themselves, not their employers past or present. 

Description: The Scaled Agile framework [https://www.scaledagile.com/](url) is one of the leading approaches to agile, with an emphasis on software engineering practices. It co-evolved with DevOps and integrates longstanding principles from XP, lean and quality disciplines, such as Plan-Do-Check-Act (the "Deming Circle") and rapid, customer-focused deployments in small chunks with maximum use of automation. Underwood and Sanyal will provide a thumbnail sketch SAFe, and discuss benefits seen for traditional software engineering processes -- from an _information security_ perspective. There are pros, cons and open issues that may be of interest to the CNCF security community considering its de facto use of relatively rapid release processes within projects and the prevalence of agile practices among developers, if not explicitly within CNCF projects themselves.

SAFe
According to its authors, SAFe is based upon nine underlying concepts, which are derived from existing lean and agile principles, as well as observation: [http://www.scaledagileframework.com/safe-lean-agile-principles/](url)

Take an economic view
Apply systems thinking
Assume variability; preserve options
Build incrementally with fast integrated learning cycles
Base milestones on objective evaluation of working systems
Visualize and limit work-in-progress, reduce batch sizes, and manage queue lengths
Apply cadence (timing), synchronize with cross-domain planning
Unlock the intrinsic motivation of knowledge workers
Decentralize decision-making
Organize around value

Time: How long will the presentation take? 40 min

Availability: Open to schedule for April or May 2020.

TO DO
- [x] SIG Representative (@lumjjb)
- [x] Schedule date: April 1 2020

**Comment by lumjjb** [comment]
How does April 8 sound ?

**Comment by lumjjb** [comment]
I noticed that this is now set in the schedule as April 1. Let me update this issue.

**Comment by dshaw** [comment]
Thanks for sharing @knowlengr. Can you link to your slides here?

**Comment by lumjjb** [comment]
Hi @knowlengr, let's put the link in and close out the issue! :)

**Comment by TheFoxAtWork** [comment]
@knowlengr reminder to post the link to the presentation so this issue may be closed.

**Comment by TheFoxAtWork** [comment]
@lumjjb recommend closing without slides.

**Comment by knowlengr** [comment]
https://www.slideshare.net/knowlengr/security-within-scaled-agile
