### ISSUE TITLE
Security Assessment for Project Harbor's Graduation Bid

### ISSUE THREAD

**Issue by michmike** [cncf/sig-security#369]
Project Name:  Harbor
Github URL: https://github.com/goharbor
Website: https://goharbor.io
Security Provider: yes

- [x] Identify team
   - [x] Project security lead: Michael Michael (michmike), Daniel Jiang (reasonerjt)
   - [x] Lead Security Reviewer: Andres Vega (anvega)
   - [x] 1 or more additional reviewer(s): Justin Cappos (justincappos), Cameron Seader (cseader), Chase Pettet (chasemp), Vinay Venkataraghavan (vinayvenkat), observer:Payam Tarverdyan Chychi (pchychi-blox), Martin Vrachev (MVrachev)
   - [x] Declaration of reading of [security reviewer guidelines](https://github.com/cncf/sig-security/blob/master/assessments/guide/security-reviewer.md) and declaration of conflits (by each reviewer)
   - [x] Sign off by 2 chairs on reviewer conflicts
- [x] Create slack channel: [#sec-assess-harbor](https://cloud-native.slack.com/messages/sec-assess-harbor)
- [x] Project lead provides draft document - see [outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md)
- [x] "Clarifying question phase" Lead Security Reviewer asks clarifying questions 
- [x] Initial review
- [x] Presentation & discussion on 4/22/2020
- [x] Share draft findings with project
- [x] Assessment summary and doc checked into /assessments/projects/project-name - [/assessments/projects/harbor](https://github.com/cncf/sig-security/blob/master/assessments/projects/harbor)
- [x] CNCF TOC presentation (Harbor did a TOC presentation on 11/05/2019. [Slides](https://docs.google.com/presentation/d/12B5dGc8lMxKeKBFS8pGoldBtZaIWBtDYUFSNcG0mnCc/edit?ts=5d9f4ab2#slide=id.g5d0c4feb44_0_0))

Document for the CNCF SIG-Security review is located at https://docs.google.com/document/d/1OiBGl2D2kBUjLEippHUPgpZgSDTFIeCwpA6RxzQJpoc/edit?usp=sharing

**Comment by michmike** [comment]
Xref: https://github.com/cncf/toc/pull/311

**Comment by anvega** [comment]
I'm happy to participate as a reviewer. I've read the guideline and have no conflict.

**Comment by cseader** [comment]
Happy to be an assessment reviewer :+1:

**Comment by chasemp** [comment]
I cannot seem to edit the top line item.  But if someone can add me as an additional reviewer that would be swell.

**Comment by pchychi-blox** [comment]
Happy to be added as an security review observer

**Comment by vinayvenkat** [comment]
I'd like to participate in the security review for Harbor.

**Comment by saravanant23** [comment]
Like participate in the security review for Harbor. Thanks

**Comment by raravena80** [comment]
For Harbor, there is a combined document created by SIG-Runtime to gather reviews and concerns from all the different SIGs: https://docs.google.com/document/d/1IxakOhnAPjN3RFn1jYLvDCAaC_-mj3n-1StJ1CKGdkM.  Can you please update the doc once you have completed the review? Thanks!

**Comment by JustinCappos** [comment]
Here is my conflict statement:

Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO (except to Notary via TUF)
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by chasemp** [comment]
Here is my conflict statement:

Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO 
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by vinayvenkat** [comment]
Here is my conflict statement:

Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO 
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by JustinCappos** [comment]
@cseader @anvega @pchychi-blox Would you please add your conflict statements?

**Comment by anvega** [comment]
I'd like to propose the following schedule:

**Comment by pchychi-blox** [comment]
Here is my conflict statement:

Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO (except to Notary via TUF)
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by JustinCappos** [comment]
> Reviewer has contributed to the project. - NO **(except to Notary via TUF)**

I didn't know you were a TUF contributor.  Was this a typo?

**Comment by JustinCappos** [comment]
@anvega Since we haven't heard from @cseader , should we move on without them?  I can remove them from the list.

**Comment by pchychi-blox** [comment]
> > **F)**
> 
> I didn't know you are a TUF contributor. Was this a typo?

My apologies, yes, and corrected.

**Comment by anvega** [comment]
@JustinCappos I pinged @cseader to see if he can respond today, while I get going on the dumb questions phase. If we don't hear back from him by tomorrow we can remove him from the list.

**Comment by cseader** [comment]
Here is my conflict statement:
Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by JustinCappos** [comment]
@ultrasaurus @pragashj @dshaw Ready for sign-off from chairs about conflicts...

**Comment by JustinCappos** [comment]
I'm signing off on the conflict statements.

**Comment by dshaw** [comment]
Co-chair sign-off confirming conflict statement reviews for @anvega @justincappos @cseader @chasemp @vinayvenkat @pchychi-blox. Thank you all.

**Comment by MVrachev** [comment]
Hopefully it isn't too late to join as an `observer` in this assessment.

Here is my conflict statement:
Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - YES
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

I wrote that I have a soft conflict with `Reviewer belongs to the same company/organization of the project, but does not work on the project` because Harbor was initially created at VMware and I work there although Harbor is no longer VMware exclusive project.

**Comment by MVrachev** [comment]
@JustinCappos @dshaw am I accepted as an observer in this assessment?

**Comment by JustinCappos** [comment]
> @JustinCappos @dshaw am I accepted as an observer in this assessment?

yes, done!

**Comment by michmike** [comment]
@anvega is the process that sig-security performs a TOC presentation for a security assessment? the other SIGs that did an assessment for Harbor's graduation bid just wrote their assessment in a doc and shared the findings. i am asking since we need to reserve the TOC slot in advance.
@caniszczyk for your thoughts as well.

**Comment by anvega** [comment]
@michmike The assessment summary once committed and merged will be used as a reference. Looking back no presentations have been made to share the summary from SIG-Security to TOC.

**Comment by michmike** [comment]
got it. thanks @anvega

**Comment by michmike** [comment]
PR for the self-assessment is at https://github.com/cncf/sig-security/pull/378

**Comment by dshaw** [comment]
Security Assessment complete. We are now finalizing due diligence documentation.

**Comment by dshaw** [comment]
Due diligence and SIG-Security's recommendation that Harbor graduate has been submitted to the TOC. https://github.com/cncf/toc/pull/311

**Comment by dshaw** [comment]
I'm going to leave this open for SIG-Security Assessment feedback and commendation with the Tech Leads in two weeks. All expected actions from the Harbor team are complete.

**Comment by JustinCappos** [comment]
> I'm going to leave this open for SIG-Security Assessment feedback and commendation with the Tech Leads in two weeks. All expected actions from the Harbor team are complete.

Looks like that time has passed!  I'll close this issue and mark this as done.
