### ISSUE TITLE
Request Briefing from Cloudbees

### ISSUE THREAD

**Issue by knowlengr** [cncf/sig-security#38]
Cloudbees is a provider of services to enhance continuous software delivery (CD/CT/CI/CF).  Their (at least partly vendor-neutral) views on best practices to enhance cloud security (including serverless) can inform guidance produced by this working group. 

I have sales contacts from attending their webinars, but if others know of specific contacts with appropriate background and savvy, please help.

Following is a snip from a Cloudbees [DevOps security blog post](https://devops.com/devops-making-development-cycle-more-secure/):
"To realize the full benefits of DevOps, organizations must deploy security or identity management technologies that are in sync with a continuous deployment/integration cycle. If identity and access management (IAM) systems cannot be deployed and managed in the same manner as your APIs and microservices, then it makes the DevOps process more cumbersome and less streamlined.
 

One technology to consider is externalized dynamic authorization delivered with attribute-based access control (ABAC). With dynamic authorization, users are authorized access to resources based on attributes. Authorization is then determined dynamically at runtime by evaluating centrally managed rules and policies.
 

With dynamic authorization, you can automate policy changes the same way you can automate code changes. In addition, the ABAC service itself can be managed like a microservice, giving it the same flexibility, deployment and automation characteristics as your application microservices. Ultimately, the life cycle of redeploying the application and security components can be fully automated. Similarly, any changes to policies can also be part of the automation process. Furthermore, you can automate the activation of additional authorization servers for peak load conditions and remove them when less capacity is required.
 

With an automated approach you can relieve pressure on developers, because they no longer will have to write security rules into their code. In addition, access rules are enforced consistently across applications, APIs, microservices and data resources, reducing the risk of overexposure to information and security breaches. This also means that your developers can spend their time on business functionality, not worrying about access security.
 

Security technologies such as dynamic authorization are a critical part of the DevOps process. With dynamic authorization embedded directly into the development cycle, organizations can automatically address a wide variety of security aspects across the enterprise and ensure a continuous and secure development cycle."

**Comment by lumjjb** [comment]
Closing from inactivity.
