### ISSUE TITLE
[Assessment] Parsec for Sandbox

### ISSUE THREAD

**Issue by amye** [cncf/sig-security#380]
Project Name: Parsec 
Github URL: https://github.com/parallaxsecond/parsec 
TOC Issue: https://github.com/cncf/toc/pull/442 (sandbox)

Security Provider: yes/no (e.g. Is the primary function of the project to support the security of an integrating system?)

- [ ] Identify team
   - [ ] Project security lead
   - [ ] Lead Security Reviewer
   - [ ] 1 or more additional reviewer(s) @anvega @rficcaglia
   - [ ] Declaration of reading of [security reviewer guidelines](https://github.com/cncf/sig-security/blob/master/assessments/guide/security-reviewer.md) and declaration of conflits (by each reviewer)
   - [ ] Sign off by 2 chairs on reviewer conflicts
- [x] Create slack channel (e.g. #sec-assess-projectname)
- [ ] Project lead provides draft document - see [outline](https://github.com/cncf/sig-security/blob/master/assessments/guide/outline.md)
- [ ] "Naive question phase" Lead Security Reviewer asks clarifying questions 
- [ ] Assign issue to security reviewers
- [ ] Initial review
- [ ] Presentation & discussion
- [ ] Share draft findings with project
- [ ] Assessment summary and doc checked into /assessments/projects/project-name (require at least 1 co-chair approval)
- [ ] CNCF TOC presentation (if requested by TOC)

**Comment by ficcaglia** [comment]
since Falco and Cloud C7n are on hold, I can take this one on.

**Comment by lumjjb** [comment]
Hi @paulhowardarm, sounds like a great project. Would you and other members of the community be able to do a presentation on this at one of the sig calls? Thanks!

**Comment by paulhowardarm** [comment]
Hi @lumjjb - sure, happy to present the project at the Wednesday SIG call whenever your schedule permits. I have presentation materials on standby and I'm good to go any time.

**Comment by lumjjb** [comment]
Awesome!  - @paulhowardarm how about 20 May? I've put it in the schedule for now. Looking forward to it!

**Comment by paulhowardarm** [comment]
@lumjjb 20th May should be good. I'll put it in my calendar.

**Comment by lumjjb** [comment]
Awesome - thanks!

**Comment by lumjjb** [comment]
Presentation link: https://drive.google.com/file/d/1GymBrSWWd8B6roayB80L5Gk41X-fDy-e/view

**Comment by anvega** [comment]
I've been looking at PARSEC in relation to its identity model. I'd be happy to participate as a reviewer. 

Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by JustinCappos** [comment]
> since Falco and Cloud C7n are on hold, I can take this one on.

 @rficcaglia , would you list your conflict statement please?

**Comment by rficcaglia** [comment]
@JustinCappos 

Hard conflicts:

Reviewer is a maintainer of the project - NO
Reviewer is a direct report of/to a maintainer of the project - NO
Reviewer is paid to work on the project - NO
Reviewer has significant financial interest directly tied to success of the project - NO

Soft conflicts:

Reviewer belongs to the same company/organization of the project, but does not work on the project - NO
Reviewer uses the project in his/her work - NO
Reviewer has contributed to the project. - NO
Reviewer has a personal stake in the project (personal relationships, etc.) - NO

**Comment by rficcaglia** [comment]
[slack channel created](https://cloud-native.slack.com/archives/C0154QH5Z43)

**Comment by rficcaglia** [comment]
@JustinCappos can we assign Lead Security Reviewer to @anvega ?

**Comment by amye** [comment]
Closing as Parsec is included as a part of Sandbox - but happy to see a new issue for incubation rise!
