### ISSUE TITLE
[Proposal] DoD Kubernetes/Container Security Proposal

### ISSUE THREAD

**Issue by timfong888** [cncf/sig-security#391]
**Description:** 
To have a comprehensive and exhaustive list of “controls” for the Department of Defense (DoD) to secure Kubernetes end-to-end programmatically (meaning it can be inspected and verified with code; and ideally fixed/patched/configured with code)

**Impact:** 
The US Air Force, in conjunction with the Linux Foundation and other parties, is developing a series of guidelines to secure their cloud infrastructure. This set of guidelines will be published as part of the DoD container deployment specification.

Helping the Air Force not only improves the security for a range of military services (e.g. going into outer space, jet fighters), but can improve the security across other industries, as well.

The resulting guidelines will not only help improve the security practices throughout the US Department of Defense, but also security-sensitive organizations like finance institutions.

One of the primary artifacts is to come up with a comprehensive checklist of policies, procedures, settings, and remediations that can be executed as code one should set up for end-to-end security in a containerized environment.

https://docs.google.com/document/d/1-FaTIVCfRSFo1mEyMV9opgOIEdst63S2EpSJTNf81h0/edit

**Scope:** 

The primary output is a spreadsheet which has a kind of IFTTT pattern for detection and remediation.

**Google version for us to add to:** https://docs.google.com/spreadsheets/d/1WwV11OlPOd6Q2FVa8Y66x3f_X9WxMN3sjFR7eQMdrjg/edit#gid=697766176

**Source in repo:**
https://repo1.dsop.io/dsawg-devsecops/kubernetes-srg/k8-srg-artifacts/-/blob/master/Consolidated%20Spreadsheet.xlsx

CNCF merged content here:
https://repo1.dsop.io/dsawg-devsecops/kubernetes-srg/k8-srg-artifacts/-/tree/master/linuxfoundation

TO DO
- [ ] Join the CNCF Slack channel (#dod-devsecops): https://cloud-native.slack.com/archives/C014DPM5CDR
- [ ] Someone volunteered to take a first stab at this across the full pipeline
- [ ] Approval process across the SIG
- [ ] Deliver to repo as part of Linux Foundation merge request

https://repo1.dsop.io/dsawg-devsecops/kubernetes-srg/k8-srg-artifacts/-/tree/master

**Comment by simar7** [comment]
Thanks for putting this up @timfong888. Is adding new items to this checklist possible from an external contributor? If so I'd like to add an item for scanning container images for vulnerabilities before deployment.

**Comment by timfong888** [comment]
@simar7 yes the goal is to add to the list!  We will represent those are part of the Linux Foundation.  What is a preferred form factor, Google sheets?

**Comment by timfong888** [comment]
I have now added the Google sheet.  I did make it require a request for access to edit in the short term, if it is too cumbersome, will make it wide open.

https://docs.google.com/spreadsheets/d/1WwV11OlPOd6Q2FVa8Y66x3f_X9WxMN3sjFR7eQMdrjg/edit#gid=697766176

**Comment by cseader** [comment]
I requested access to the spreadsheet. Please allow access.

**Comment by chasemp** [comment]
It seems appropriate to add a default LICENSE file to the repo at https://repo1.dsop.io/dsawg-devsecops/kubernetes-srg/k8-srg-artifacts ?  It would be much better to do this early than to try to revisit down the road as questions of distribution, updating, and reuse come up.

I suggest: 

- https://creativecommons.org/licenses/by/4.0/
- https://creativecommons.org/licenses/by/3.0/

**Comment by timfong888** [comment]
https://lists.cncf.io/g/cncf-sig-security/message/26

**Comment by chasemp** [comment]
Thanks @timfong888
