### ISSUE TITLE
[Proposal] Clearly establish the goals and non-goals of the Security Assessments

### ISSUE THREAD

**Issue by vinayvenkat** [cncf/sig-security#395]
Description: The objectives, goals and non-goals of security assessments of graduating projects have not clearly documented. The intent of this proposal is to clearly document and articulate these objectives as well as establish who the stakeholders of these assessments are.

Impact: 
The impact of this proposal are:

- help to educate new members as to the objectives, goals and non-goals of the security assessments. 

- help to provide a framework for members participating on a security assessment on the objectives and to help focus the activities around the objectives. 

- help to establish the stakholders of the security assessment. 

- help readers to understand the key takeaways and implications of the security assessment. 

Scope: 

Would need to discuss the goals and non-goals with members who have performed security assessments in the past to determine these goals. 

Get input from different members on their perspectives for security assessments. 

TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by TheFoxAtWork** [comment]
Added assessment-process label to ensure this is captured in those activities  CC @lumjjb

**Comment by lumjjb** [comment]
Closing this issue in favor of https://github.com/cncf/sig-security/issues/444, which should capture the items from here.
