### ISSUE TITLE
[Presentation] Checkov

### ISSUE THREAD

**Issue by schosterbarak** [cncf/sig-security#403]
Title: What is the title of your presentation?

Checkov

Speakers: Who will be presenting this? List names/github IDs of presenters.
Schoster Barak @schosterbarak 
Guy Eisenkot @guyeisenkot 

Description: Describe in a short paragraph what the presentation is about.

Checkov is a static analysis tool for infrastructure as code. It works across several IaC frameworks such as Terraform, Cloudformation, Kubernetes and Serverless framework.

https://www.checkov.io/
https://github.com/bridgecrewio/checkov 

Time: How long will the presentation take? (estimate)
30m

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page. 
July 1st 2020
July 8th 2020

TO DO
- [x] SIG Representative - @lumjjb 
- [x] Schedule date - July 8th 2020

**Comment by lumjjb** [comment]
Hi @schosterbarak , i'll pen you in for July 8th. Sounds good?

**Comment by schosterbarak** [comment]
@lumjjb That would be amazing! 
Any additional prep required before presenting (outside of making the ppt)?

**Comment by lumjjb** [comment]
nope, all good, looking forward to your presentation!

**Comment by lumjjb** [comment]
@schosterbarak thanks for the presentation - can you put a link to the slides here as well? Thanks!

**Comment by lumjjb** [comment]
Presentation done on July 8th
