### ISSUE TITLE
Create merged agenda uniting the SAFE WG and Policy WG teams

### ISSUE THREAD

**Issue by dshaw** [cncf/sig-security#41]
The SAFE WG will be presenting to the CNCF TOC on Tuesday, August 21. The Kubernetes Policy WG has formed a team focused on bringing Cloud Native Policy context back to Kubernetes. Given the overlap between our teams, we are banding together to form one unified group under SAFE.

The agendas of the two groups need to be merged.

**Comment by dshaw** [comment]
WIP Document: [SAFE Working Group Merged Agenda](https://docs.google.com/document/d/14A-0RWyf5F35i7ZCmwLM-eaCq9aLv_I-pdO-kWdM0zk/edit)

The document should be world readable and open for comment. Please feel free to request edit access as needed.

**Comment by lumjjb** [comment]
Looks like this issue is resolved by https://github.com/cncf/sig-security/pull/42
