### ISSUE TITLE
Keylime Project

### ISSUE THREAD

**Issue by lukehinds** [cncf/sig-security#411]
Title: Keylime CNCF Project Proposal

Speakers: 

Luke Hinds @lukehinds 
Charles Munson @jetwhiz

Description: The presentation will be made as part of Keylimes proposal to join the CNCF as a project. The pull request is available here https://github.com/cncf/toc/pull/496

Time: 20 minutes

Availability: 

Available at all times, although Luke Hinds will be on PTO from the 10th to the 24th of August.

TO DO
- [x] SIG Representative: @lumjjb 
- [x] Schedule date: Oct 14

**Comment by lumjjb** [comment]
Hi @lukehinds and @jetwhiz, this is a bit short notice, but would August 5th (tomorrow be okay for you - the usual sig-security meeting time).

**Comment by lukehinds** [comment]
@lumjjb I am ok with this, let me email charlie to see if he is free!

**Comment by amye** [comment]
Note: Keylime is being proposed as a sandbox project, so SIG review is not required here: https://github.com/cncf/toc/pull/496

**Comment by lumjjb** [comment]
@lukehinds any word from Charlie? If not let's try for when you're back from PTO (and after kubecon week), so we leave enough time to get the word out on the presentation.

**Comment by lukehinds** [comment]
> @lukehinds any word from Charlie? If not let's try for when you're back from PTO (and after kubecon week), so we leave enough time to get the word out on the presentation.

Hey Brandon, seems I don't need to present to the sig now. It goes direct to the TOC who make the decision.

**Comment by lumjjb** [comment]
Sounds good - I think it would still be an interesting topic to share, but not so much of a time constraint i guess :). Just a heads up, for whenever incubation comes around, the sig approval process is based on: https://github.com/cncf/sig-security/tree/master/assessments

**Comment by lumjjb** [comment]
Hi @lukehinds! Congratulations on sandbox!! Would you be available to do a presentation on Oct 14?

**Comment by lukehinds** [comment]
> Hi @lukehinds! Congratulations on sandbox!! Would you be available to do a presentation on Oct 14?

my pleasure, I still have the deck I was going to use for the sig.

**Comment by lumjjb** [comment]
Great - i've put keylime down for the next available slot on Oct 14!

**Comment by lukehinds** [comment]
@lumjjb et al,

my presentation: 

https://docs.google.com/presentation/d/1n00Ny1fc-tDRtRb-Yf66mTs4sM7iOY2YW7-fhFaS2Yc
