### ISSUE TITLE
[Suggestion] Establish Criteria and Boundaries for Security Assessment

### ISSUE THREAD

**Issue by chubirka** [cncf/sig-security#415]
**Description:** Provide clearer criteria and boundaries for Security Assessment process or rename it. 

**Impact:** The current Security Assessment process is unclear, therefore the artifacts are inconsistent. Additionally, having the project owner/lead deliver an assessment is not considered a "best practice."

**Scope:** Either create a clearer SOP for the assessment process or convert into a Security Overview document. 

Additional info:
https://github.com/cncf/sig-security/issues/395
https://github.com/cncf/sig-security/issues/394

**Comment by lumjjb** [comment]
Hi @chubirka , it would help if you can provide some examples of this in context of https://github.com/cncf/sig-security/tree/master/assessments/guide

>Additionally, having the project owner/lead deliver an assessment is not considered a "best practice."

Are you referring to the self-assessment? This document is used as an initial form to fill out more information about the project. Kind of similar to how an application owner would submit a security questionnaire for internal review. Security reviewers then do due diligence on this document and modify it based on their findings - it is not accepted at face value.

That said, the extensiveness of the assessment cannot fully protect against malicious project owners. This is a limitation of resources and scope, but if reviewers identify that something is amiss, a recommendation to the CNCF can be done to perform a security audit. 

Is this what you are referring to, or are you thinking about a different perspective?

**Comment by TheFoxAtWork** [comment]
I want to bring this into a working meeting with Issue #254 and #394

**Comment by chubirka** [comment]
> Hi @chubirka , it would help if you can provide some examples of this in context of https://github.com/cncf/sig-security/tree/master/assessments/guide
> 
> 
> 
> >Additionally, having the project owner/lead deliver an assessment is not considered a "best practice."
> 
> 
> 
> Are you referring to the self-assessment? This document is used as an initial form to fill out more information about the project. Kind of similar to how an application owner would submit a security questionnaire for internal review. Security reviewers then do due diligence on this document and modify it based on their findings - it is not accepted at face value.
> 
> 
> 
> That said, the extensiveness of the assessment cannot fully protect against malicious project owners. This is a limitation of resources and scope, but if reviewers identify that something is amiss, a recommendation to the CNCF can be done to perform a security audit. 
> 
> 
> 
> Is this what you are referring to, or are you thinking about a different perspective?

I'm referring to the security assessment. While that template has a section to disclose conflicts, one would typically not have a security assessment performed by the project owner as it violates separation of duties. Maybe I'm missing something, but if you're saying that the security assessment is divided into two distinct phases, the first performed by the project owner do to document the security areas of concern and a second review of this material performed by an unconnected group of individuals, that didn't seem clear to me. I would recommend a more detailed job aid or procedure document to break this up. My comment was intended to improve transparency of the process.

**Comment by JustinCappos** [comment]
You do make a valid point that letting the project being reviewed provide the material does have some potential for misuse, error, etc.  Given the assessors are often unfamiliar with the project (and have full time jobs doing other things), we haven't really thought of a better way to address this issue.  Do you have some thoughts?

I do also think we're likely just not being clear in the documentation.  It isn't so much that the project owner performs the assessment,  it's that they produce a document which we collectively later evolve into part of the assessment.  The project's document is listed as the project's self assessment even though the security assessors contribute heavily to the document. 
We have two separate documents so that the project has editorial control of one document (the self-assessment) and the assessors have editorial control of another document.  This helps to prevent either side from needing to fight over the content in a shared document because they each have their place to make a point.

**Comment by lumjjb** [comment]
There is a review of assessments that is set to happen after keycloak's assessment completion. Linking the issue for tracking during review: https://github.com/cncf/sig-security/issues/167.

**Comment by lumjjb** [comment]
The context of topics in these issues are now being covered by the following issues that spun up from Sec assess. WG

https://github.com/cncf/sig-security/issues/449
https://github.com/cncf/sig-security/issues/444

So closing this in favor of contributing to those, which are more scoped.
