### ISSUE TITLE
[Suggestion] revise the meeting notes scribe template

### ISSUE THREAD

**Issue by itaysk** [cncf/sig-security#426]
Description: In the meeting notes document, we have a table template for each meeting scribes. It has 2 columns for 2 scribes, and rows for each topic, so that a reader can browse rows and get both scribes' perspectives. That's great. What I don't get is the prepared rows categories, that the scribes need to fill. In practice though, most of the meeting just goes in the `General standup and check-ins from partner SIGs and WGs` box. Here are the current categories:

1. Attendance and designating scribes.
2. General standup and check-ins from partner SIGs and WGs.
3. Issues/PRs for discussion.
4. Whitepaper Update:
5. Github PR:
6. Security assessment process
6. Issues/PRs requiring chair approval.
7. General discussions (open the floor).

I suggest to simplify the table. Keep the 2 column format, and row per topic, but let the scribes add rows as needed (which is what happens anyway)

Impact: Describe your hopes for how this would reduce risk for the cloud native ecosystem. Who will this help? How will it help them?
It will help scribes be more effective and readers read the meeting notes easily

Scope: How much effort will this take? ok to provide a range of options if or "not yet determined" 
Very easy

Additional info:
https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/edit#

**Comment by TheFoxAtWork** [comment]
Love this!  @lumjjb @lumjjb @JustinCappos @ultrasaurus do think this would be good to try out at the next two meetings?  a simplified table?

**Comment by TheFoxAtWork** [comment]
I went ahead and made the revision to the template @itaysk if you are on todays call, and willing to scribe please let us know if this works better. i plan on discussing it.

**Comment by TheFoxAtWork** [comment]
Closing issue as the change was made and appears to be satisfactory.
