### ISSUE TITLE
[Presentation]  CSA Serverless Security

### ISSUE THREAD

**Issue by lumjjb** [cncf/sig-security#437]
Title: What is the title of your presentation?

CSA Serverless Security

Speakers: Who will be presenting this? List names/github IDs of presenters.

Aradhna Chetal

Description: Describe in a short paragraph what the presentation is about.

Time: How long will the presentation take? (estimate) 20-30 mins

Availability: What is the availability times of the speakers to present the topic? Meeting times are listed on the landing page. 

TO DO
- [x] SIG Representative @pragashj 
- [x] Schedule date Oct 21 2020

**Comment by achetal01** [comment]
Here is the Slide deck for today's presentation.

Thank You 
[CSA Serverless PResentation V1.0.pptx](https://github.com/cncf/sig-security/files/5420002/CSA.Serverless.PResentation.V1.0.pptx)
[CSA Serverless PResentation V1.0.pptx](https://github.com/cncf/sig-security/files/5420008/CSA.Serverless.PResentation.V1.0.pptx)

**Comment by lumjjb** [comment]
Presentation done! closing issue.
