### ISSUE TITLE
policy monitoring and enforcement

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#46]
I don't think we've had any presentations from vendors or projects doing any kind of security auditing or policy checking.  I think this would be a good perspective to inform our work.

Two open source projects that could provide good perspectives on this:
* Forseti: https://forsetisecurity.org/
* Cloud Custodian: https://github.com/capitalone/cloud-custodian

**Comment by rficcaglia** [comment]
Someone from cloud custodian was on a Policy WG call a few weeks back.  @hannibalhuang do you have his info?  Perhaps we can invite him to present? He expressed interest in learning more about how they can support k8s.

**Comment by ultrasaurus** [comment]
Cloud Custodian presentation scheduled (Dec 11): https://github.com/cncf/sig-security/issues/300

**Comment by TheFoxAtWork** [comment]
Closing this issue as we have an ongoing assessment for cloud custodian (ref 20200920 meeting notes)
