### ISSUE TITLE
White Paper - Broken links, duplicate content

### ISSUE THREAD

**Issue by jlk** [cncf/sig-security#464]
Several links in the Cloud Native Security whitepaper go to one or more google docs that are not accessible, resulting in a page with "Sorry, unable to open the file at this time":

* Page 15, under _Image Hardening_, the link to "security assessment objectives" loads a Google docs 
* Also a broken link in last sentence on p22: "identity portion of this paper"
* Page 27, under Boostrapping - "Trust" link is broken.
* Page 28, links under Orchestration
* Page 30, "key management" link in 2nd paragraph.
* Page 31, "least privilege" in 4th paragraph.
(I don't mean this list to be comprehensive, but I noticed these as I read the doc)

Also, page 25 looks like a duplicate from pages 6/7...

**Comment by jlk** [comment]
Also a dead link in last sentence on p22: "identity portion of this paper"

**Comment by jlk** [comment]
Also, _Introduction_ and _Target Audience_ sections are on both pages 7 and 25...

**Comment by jlk** [comment]
Page 27, under _Boostrapping_ - "Trust" link is broken.

**Comment by jlk** [comment]
Page 28, links under _Orchestration_

**Comment by jlk** [comment]
Page 30, "key management" link in 2nd paragraph.
Page 31, "least privilege" in 4th paragraph.

**Comment by TheFoxAtWork** [comment]
@jlk Thanks for the feed back!  We caught it after we release it and the latest version should have the links stripped (from converting a google doc with internal bookmarks to PDF with amazing graphics).  Regarding page 25, The executive summary is designed to provide a high level overview of the entire doc so some content may look duplicate.  I expect our next iteration will expand these areas in the later part of the document.
