### ISSUE TITLE
document our governance model

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/sig-security#47]
We talked about this, but didn't include in the repo.

@pragashj volunteered to submit a PR

**Comment by pragashj** [comment]
The governance document is a WIP and is going to be loosely based on SIG-Auth. Any inputs to this from the community is welcome.

**Comment by ultrasaurus** [comment]
there has been a lot of work in /governance -- closing as completed.  Any additional concerns should be opened as specific issues.
