### ISSUE TITLE
White Paper Footnotes Off-By-One in PDF

### ISSUE THREAD

**Issue by apmarshall** [cncf/sig-security#500]
This is a very minor thing, but also probably a very easy fix.

I noticed when reading through the White Paper that the footnotes were off-by-one starting with what should be footnote 4. Essentially, what happens is that the first 3, found in the Executive Summary are correctly ordered. Then, on page 8 of the PDF, the number in the document is one ahead of the number in the footer (so in the doc body, it says `4` and in the footer it says `3`). Then, on page 11, the document repeats footnote `4`, and the numbers in the footer start matching up again (repeating `4`). So the sequence in the document is `1, 2, 3, 4, 4, 5, 6...` and in the footers is `1, 2, 3, 3, 4, 5, 6...`

I assumed this would be duplicated in the Markdown Version, but actually in the MD file the numbers all appear to be correct in both the document body and the actual footnotes/endnotes. So the issue is unique to the PDF version. I don't see where that is being generated from (maybe a Google Doc or MS Word document that isn't in the repo), but whatever its source that appears to be where the sequencing is out of sync.

Like I said, very minor/trivial issue and hopefully an easy fix for whenever the next edition comes out.

**Comment by TheFoxAtWork** [comment]
Yep!  we are aware of it and plan to fix it in the next update.  thank you for the issue!
