### ISSUE TITLE
[Presentation] LF/CNCF Security Scanning

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/sig-security#512]
Title: LF/CNCF Security Scanning

Speakers: Shubhra Kar

Description: Describe in a short paragraph what the presentation is about.

Time: How long will the presentation take? (estimate)

Availability: February 3rd.

TO DO
- [x] SIG Representative
- [x] Shubhra Kar

**Comment by ShubhraKar** [comment]
Title: LF/CNCF Security Scanning

Speakers: Shubhra Kar

Description: Security is a top challenge for open source projects. The Linux Foundation engineering team has been working on a toolkit called LFX Security that provides automated scanning to detect vulnerabilities and weaknesses in the native and upstream packages, proposing fixes, and to help projects address top security concerns. LFX is freely available to all LF projects to use. Roadmap includes badging, SBOM and more. 

Time: 25 minutes

Availability: February 3rd.

**Comment by lumjjb** [comment]
Hi @ShubhraKar, thanks for the great presentation and great discussions! Are there any links to slides that you can share?

**Comment by ShubhraKar** [comment]
Thanks for inviting me. Looking forward to collaborating. Link to presentation: https://docs.google.com/presentation/d/1nTkeYi3TRDEb1uklFM5-f0BSJ4Yu7f1H-Xc4JHx2lrY/edit?usp=sharing
