### ISSUE TITLE
[Presentation] Jen Burns to speak about MITRE ATT&CK for Containers

### ISSUE THREAD

**Issue by magnologan** [cncf/sig-security#513]
Title: [MITRE ATT&CK for Containers](https://medium.com/mitre-engenuity/help-shape-att-ck-for-containers-7fe4905623c5) 

Speakers: [Jen Burns, Lead Cybersecurity Engineer, ATT&CK for Cloud Lead at MITRE](https://www.linkedin.com/in/burnsjennifere/)

Description: The MITRE ATT&CK team is investigating adversarial behavior in containers for potential inclusion in ATT&CK. If they find that there’s enough adversary behavior in containers to warrant ATT&CK coverage, they’ll consider that content for a future ATT&CK release. This presentation aims to share some information about the project and provide some details on how CNCF and the SIG-Security team could help with this project.

Time: 15-20 min

Availability: Feb 10th, 1pm - 2pm 

- SIG Representative: @magnologan (TL/Chair: @lumjjb )
- Schedule date: Feb 10th, 1pm - 2pm

**Comment by lumjjb** [comment]
Hi @magnologan, assuming you can help coordinate with the speaker. :) Looking forward to this topic!

**Comment by magnologan** [comment]
@lumjjb Yes, I've coordinated with Jen and she has agreed to speak on this date and time. I'll keep you posted if anything changes. Thanks!

**Comment by magnologan** [comment]
This has been cancelled for today as Jen won't be able to  attend or send a replacement. We'll coordinate the rescheduling with her next week and update the ticket with a future date. Thank you!

**Comment by knowlengr** [comment]
Looking forward to this event - a lead time of at least a meeting or two would be helpful.

**Comment by lumjjb** [comment]
Needs a new date for this - @magnologan let us know when we can reschedule this to!

**Comment by magnologan** [comment]
New date scheduled for March 17th @ 1pm ET. @lumjjb
