### ISSUE TITLE
Cloud Native Security Day EU blog draft

### ISSUE THREAD

**Issue by TheFoxAtWork** [cncf/sig-security#547]
Description: We'd like a member of SIG-Security to draft a blog post to promote and discussion cloud native security day EU adhering to the [CNCF Blog Guidelines](https://github.com/cncf/foundation/blob/master/blog-guidelines.md) .

- [ ] blog draft is created as a comment on this issue.
- [ ] tag @anvega and the chairs (@TheFoxAtWork , @ultrasaurus , @pragashj ) for review & LGTM
- [ ] once LGTM, then submit via the guidelines

Impact: Reach a wider audience with potential interest in attending

Scope: Shouldn't take more than an hour or two for a write up.

**Comment by magnologan** [comment]
@TheFoxAtWork  I can start working on it!

**Comment by magnologan** [comment]
Sorry for the delay here, I should have the draft done by this weekend, the document that I've created to work on this is here: https://docs.google.com/document/d/1hKEgBrrvcPtCW72B1ZsF3CfDiYNkRQa_OUBBet7WmZc/edit

**Comment by TheFoxAtWork** [comment]
@magnologan checking to see fi this was done and submitted?

**Comment by magnologan** [comment]
yes it was: https://www.cncf.io/blog/2021/03/24/cloud-native-security-day-protecting-our-cloud-native-world-one-container-at-a-time/

Closing this! Thanks for reminding me!

**Comment by magnologan** [comment]
It seems I can't close the issue even though I'm the one assigned to?
