### ISSUE TITLE
[k8s/wg-policy] External systems in control

### ISSUE THREAD

**Issue by ericavonb** [cncf/sig-security#59]
The Kubernetes Policy Working Group has been discussing how to deal with external policy control systems in clusters.
Thread: [Kubernetes developer/contributor discussion › External systems in control - interest in WG?](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-dev/st1ZtD6lMFo/YXO9STkbEgAJ)

@k82cn is working on a doc to gather thoughts/requirements.

- [ ] Share doc and outcomes from these discussions with the SAFE working group 

From [Kubernetes Policy WG Meeting Notes/Agenda](https://docs.google.com/document/d/1ihFfEfgViKlUMbY2NKxaJzBkgHh-Phk5hqKTzK-NEEs/edit#)
> It was suggested that we consider looking at this slightly differently:
> * Consider a 3rd party policy checking system, where the check might be long-running
> * In that case incoming K8s requests may need to delayed/buffered/cached/something until the 3rd party system can perform its checks
> * This is similar to webhooks/admission-controllers except that those don’t allow for a long-running check to be done. If K8s recycles during that process then the request will be lost. If there were a way to support long-running checks then we may have a solution for svc-cat’s issue

cc @lizrice

**Comment by lumjjb** [comment]
Closed due to inactivity.
