### ISSUE TITLE
CNCF voting has begun

### ISSUE THREAD

**Issue by dshaw** [cncf/sig-security#71]
Chris Aniszczyk has kicked off voting to ratify SAFE WG ahead of the 2018-09-04 TOC meeting.

https://lists.cncf.io/g/cncf-toc/message/2316

**Comment by ultrasaurus** [comment]
voting is now on the [SIG proposal](https://lists.cncf.io/g/cncf-toc/topic/vote_cncf_sigs_proposal/30503071?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,30503071) where we expect security working group (maybe us?) to be the first test case

**Comment by ultrasaurus** [comment]
FYI - I updated original SAFE PR from @pragashj to refer to /governance which now addresses new [SIG process](https://github.com/cncf/toc/blob/master/sigs/cncf-sigs.md) 

TOC  voting here:  https://lists.cncf.io/g/cncf-toc/topic/31833460#3300 -- non-binding votes from the community are welcome

**Comment by ultrasaurus** [comment]
The CNCF Security SIG has been approved: https://lists.cncf.io/g/cncf-toc/message/3368
