### ISSUE TITLE
Breaking down the tasks in Policy-WG to spin off sub tasks

### ISSUE THREAD

**Issue by pragashj** [cncf/sig-security#77]
@hannibalhuang Creating this tasks as discussed in the call today.
The objective is to break the policy proposal down in to smaller iterable chunks

**Comment by lumjjb** [comment]
Hi @pragashj , is this ongoing/evolved into other issues? Can we close this issue?

**Comment by hannibalhuang** [comment]
i think we could close this, this is pretty old

**Comment by lumjjb** [comment]
Thanks @hannibalhuang , closing this issue!
