### ISSUE TITLE
SAFE in the Context of Continuous Integration/Deployment

### ISSUE THREAD

**Issue by knowlengr** [cncf/sig-security#90]
The advent of DevOps and the roots of agile have meant decreased cycle time for release - generally represented as CI/CD to reflect integration and deployment. Because DevOps adds facets of Ops and infrastructure to the mix, risks can be elevated. New threat models emerge. An example of this is containers, where visibility to traditional security tools has only recently been added (StackRox, Twistlock, Aqua etc.). Both for assurance and safety, as well as to maintain the cadence desired for CI/CD (consider the frequency of mobile app updates, for instance), CI/CD involves both new and tweaked/refreshed techniques. In particular, left-shifting of test harnesses, automated testing and test evaluation, and provisioning for dev/test/QA/prod environments that may be app-specific are all within the purview of InfoSec, especially in the scalable setting offered in the cloud environment.

In the Google and Netflix reported (via YouTube presentations) test environment, thousands of tests are run and assessed daily. This is clearly a paradigm shift, and for most everyone else with more limited resources, will present both governance, assurance and scalability challenges.

REFERENCES (to follow)

**Comment by lumjjb** [comment]
Closed due to inactivity.
