### ISSUE TITLE
SPIFFE / SPIRE Audit Retrospective

### ISSUE THREAD

**Issue by dshaw** [cncf/sig-security#97]
Justin Cappos is invited to present the prior art of pre-acceptance security audits for SPIFFE / SPIRE.

**Comment by dshaw** [comment]
Follow-up from Justin:
**[Security Audit Guidelines for SAFE WG](https://docs.google.com/document/d/1nKCGDd0TzQcVgrDWWa1t54a1E_6fwZQaFcAK-YJK2CM/edit)**

Please review and comment.

**Comment by lumjjb** [comment]
Closing this due to no action required.
